-- =====================================================
-- FLASHQI COMPLETE SEED DATA (ALL HSK LEVELS)
-- Run this in Supabase SQL Editor AFTER running supabase-schema.sql
-- Safe to re-run: uses ON CONFLICT to upsert
-- =====================================================

-- =====================================================
-- HSK 1 — Beginner (150 words)
-- =====================================================
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (1, 1, '你好', 'nǐ hǎo', 'hello'),
  (1, 2, '谢谢', 'xiè xie', 'thank you'),
  (1, 3, '再见', 'zài jiàn', 'goodbye'),
  (1, 4, '对不起', 'duì bu qǐ', 'sorry'),
  (1, 5, '是', 'shì', 'yes/to be'),
  (1, 6, '不', 'bù', 'no/not'),
  (1, 7, '我', 'wǒ', 'I/me'),
  (1, 8, '你', 'nǐ', 'you'),
  (1, 9, '他', 'tā', 'he/him'),
  (1, 10, '她', 'tā', 'she/her'),
  (1, 11, '们', 'men', 'plural marker'),
  (1, 12, '这', 'zhè', 'this'),
  (1, 13, '那', 'nà', 'that'),
  (1, 14, '什么', 'shén me', 'what'),
  (1, 15, '谁', 'shuí', 'who'),
  (1, 16, '哪', 'nǎ', 'which/where'),
  (1, 17, '多少', 'duō shao', 'how many'),
  (1, 18, '几', 'jǐ', 'how many/several'),
  (1, 19, '怎么', 'zěn me', 'how'),
  (1, 20, '怎么样', 'zěn me yàng', 'how about'),
  (1, 21, '一', 'yī', 'one'),
  (1, 22, '二', 'èr', 'two'),
  (1, 23, '三', 'sān', 'three'),
  (1, 24, '四', 'sì', 'four'),
  (1, 25, '五', 'wǔ', 'five'),
  (1, 26, '六', 'liù', 'six'),
  (1, 27, '七', 'qī', 'seven'),
  (1, 28, '八', 'bā', 'eight'),
  (1, 29, '九', 'jiǔ', 'nine'),
  (1, 30, '十', 'shí', 'ten'),
  (1, 31, '零', 'líng', 'zero'),
  (1, 32, '百', 'bǎi', 'hundred'),
  (1, 33, '爸爸', 'bà ba', 'father'),
  (1, 34, '妈妈', 'mā ma', 'mother'),
  (1, 35, '儿子', 'ér zi', 'son'),
  (1, 36, '女儿', 'nǚ ér', 'daughter'),
  (1, 37, '老师', 'lǎo shī', 'teacher'),
  (1, 38, '学生', 'xué shēng', 'student'),
  (1, 39, '朋友', 'péng you', 'friend'),
  (1, 40, '医生', 'yī shēng', 'doctor'),
  (1, 41, '人', 'rén', 'person'),
  (1, 42, '大', 'dà', 'big'),
  (1, 43, '小', 'xiǎo', 'small'),
  (1, 44, '多', 'duō', 'many'),
  (1, 45, '少', 'shǎo', 'few'),
  (1, 46, '好', 'hǎo', 'good'),
  (1, 47, '高兴', 'gāo xìng', 'happy'),
  (1, 48, '冷', 'lěng', 'cold'),
  (1, 49, '热', 'rè', 'hot'),
  (1, 50, '漂亮', 'piào liang', 'beautiful'),
  (1, 51, '吃', 'chī', 'eat'),
  (1, 52, '喝', 'hē', 'drink'),
  (1, 53, '去', 'qù', 'go'),
  (1, 54, '来', 'lái', 'come'),
  (1, 55, '看', 'kàn', 'look/see'),
  (1, 56, '听', 'tīng', 'listen'),
  (1, 57, '说', 'shuō', 'speak'),
  (1, 58, '读', 'dú', 'read'),
  (1, 59, '写', 'xiě', 'write'),
  (1, 60, '学', 'xué', 'learn'),
  (1, 61, '工作', 'gōng zuò', 'work'),
  (1, 62, '住', 'zhù', 'live'),
  (1, 63, '买', 'mǎi', 'buy'),
  (1, 64, '开', 'kāi', 'open'),
  (1, 65, '坐', 'zuò', 'sit'),
  (1, 66, '叫', 'jiào', 'call/named'),
  (1, 67, '爱', 'ài', 'love'),
  (1, 68, '想', 'xiǎng', 'think/want'),
  (1, 69, '认识', 'rèn shi', 'know (person)'),
  (1, 70, '会', 'huì', 'can/will'),
  (1, 71, '能', 'néng', 'can/able'),
  (1, 72, '有', 'yǒu', 'have'),
  (1, 73, '在', 'zài', 'at/in'),
  (1, 74, '做', 'zuò', 'do/make'),
  (1, 75, '睡觉', 'shuì jiào', 'sleep'),
  (1, 76, '水', 'shuǐ', 'water'),
  (1, 77, '茶', 'chá', 'tea'),
  (1, 78, '米饭', 'mǐ fàn', 'rice'),
  (1, 79, '水果', 'shuǐ guǒ', 'fruit'),
  (1, 80, '苹果', 'píng guǒ', 'apple'),
  (1, 81, '菜', 'cài', 'dish/vegetable'),
  (1, 82, '猫', 'māo', 'cat'),
  (1, 83, '狗', 'gǒu', 'dog'),
  (1, 84, '书', 'shū', 'book'),
  (1, 85, '电脑', 'diàn nǎo', 'computer'),
  (1, 86, '电视', 'diàn shì', 'TV'),
  (1, 87, '电影', 'diàn yǐng', 'movie'),
  (1, 88, '手机', 'shǒu jī', 'phone'),
  (1, 89, '钱', 'qián', 'money'),
  (1, 90, '飞机', 'fēi jī', 'airplane'),
  (1, 91, '出租车', 'chū zū chē', 'taxi'),
  (1, 92, '车', 'chē', 'car'),
  (1, 93, '学校', 'xué xiào', 'school'),
  (1, 94, '医院', 'yī yuàn', 'hospital'),
  (1, 95, '商店', 'shāng diàn', 'store'),
  (1, 96, '饭馆', 'fàn guǎn', 'restaurant'),
  (1, 97, '家', 'jiā', 'home'),
  (1, 98, '中国', 'zhōng guó', 'China'),
  (1, 99, '北京', 'Běi jīng', 'Beijing'),
  (1, 100, '天气', 'tiān qì', 'weather'),
  (1, 101, '下雨', 'xià yǔ', 'rain'),
  (1, 102, '今天', 'jīn tiān', 'today'),
  (1, 103, '明天', 'míng tiān', 'tomorrow'),
  (1, 104, '昨天', 'zuó tiān', 'yesterday'),
  (1, 105, '现在', 'xiàn zài', 'now'),
  (1, 106, '时候', 'shí hou', 'time/moment'),
  (1, 107, '年', 'nián', 'year'),
  (1, 108, '月', 'yuè', 'month'),
  (1, 109, '日', 'rì', 'day'),
  (1, 110, '星期', 'xīng qī', 'week'),
  (1, 111, '点', 'diǎn', 'o''clock'),
  (1, 112, '分钟', 'fēn zhōng', 'minute'),
  (1, 113, '前面', 'qián miàn', 'front'),
  (1, 114, '后面', 'hòu miàn', 'back/behind'),
  (1, 115, '里面', 'lǐ miàn', 'inside'),
  (1, 116, '上', 'shàng', 'up/on'),
  (1, 117, '下', 'xià', 'down/under'),
  (1, 118, '很', 'hěn', 'very'),
  (1, 119, '也', 'yě', 'also'),
  (1, 120, '都', 'dōu', 'all'),
  (1, 121, '没', 'méi', 'not/no'),
  (1, 122, '和', 'hé', 'and'),
  (1, 123, '的', 'de', 'possessive particle'),
  (1, 124, '了', 'le', 'completed action'),
  (1, 125, '吗', 'ma', 'question particle'),
  (1, 126, '呢', 'ne', 'modal particle'),
  (1, 127, '个', 'gè', 'measure word'),
  (1, 128, '岁', 'suì', 'years old'),
  (1, 129, '块', 'kuài', 'yuan/piece'),
  (1, 130, '本', 'běn', 'MW for books'),
  (1, 131, '些', 'xiē', 'some'),
  (1, 132, '请', 'qǐng', 'please'),
  (1, 133, '太', 'tài', 'too (much)'),
  (1, 134, '对', 'duì', 'correct'),
  (1, 135, '名字', 'míng zi', 'name'),
  (1, 136, '衣服', 'yī fu', 'clothes'),
  (1, 137, '杯子', 'bēi zi', 'cup'),
  (1, 138, '桌子', 'zhuō zi', 'table'),
  (1, 139, '椅子', 'yǐ zi', 'chair'),
  (1, 140, '东西', 'dōng xi', 'thing'),
  (1, 141, '字', 'zì', 'character'),
  (1, 142, '汉语', 'hàn yǔ', 'Chinese language'),
  (1, 143, '中午', 'zhōng wǔ', 'noon'),
  (1, 144, '早上', 'zǎo shang', 'morning'),
  (1, 145, '下午', 'xià wǔ', 'afternoon'),
  (1, 146, '晚上', 'wǎn shang', 'evening'),
  (1, 147, '小姐', 'xiǎo jiě', 'miss'),
  (1, 148, '先生', 'xiān sheng', 'mister'),
  (1, 149, '不客气', 'bú kè qi', 'you''re welcome'),
  (1, 150, '没关系', 'méi guān xi', 'it doesn''t matter')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

-- =====================================================
-- HSK 2 — Elementary (150 words)
-- =====================================================
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (2, 1, '因为', 'yīn wèi', 'because'),
  (2, 2, '所以', 'suǒ yǐ', 'so/therefore'),
  (2, 3, '但是', 'dàn shì', 'but'),
  (2, 4, '虽然', 'suī rán', 'although'),
  (2, 5, '如果', 'rú guǒ', 'if'),
  (2, 6, '已经', 'yǐ jīng', 'already'),
  (2, 7, '可以', 'kě yǐ', 'can/may'),
  (2, 8, '可能', 'kě néng', 'possible'),
  (2, 9, '需要', 'xū yào', 'need'),
  (2, 10, '应该', 'yīng gāi', 'should'),
  (2, 11, '必须', 'bì xū', 'must'),
  (2, 12, '知道', 'zhī dào', 'know'),
  (2, 13, '觉得', 'jué de', 'feel/think'),
  (2, 14, '希望', 'xī wàng', 'hope'),
  (2, 15, '相信', 'xiāng xìn', 'believe'),
  (2, 16, '帮助', 'bāng zhù', 'help'),
  (2, 17, '准备', 'zhǔn bèi', 'prepare'),
  (2, 18, '开始', 'kāi shǐ', 'begin'),
  (2, 19, '完成', 'wán chéng', 'finish'),
  (2, 20, '问', 'wèn', 'ask'),
  (2, 21, '回答', 'huí dá', 'answer'),
  (2, 22, '告诉', 'gào su', 'tell'),
  (2, 23, '介绍', 'jiè shào', 'introduce'),
  (2, 24, '等', 'děng', 'wait'),
  (2, 25, '找', 'zhǎo', 'find/look for'),
  (2, 26, '给', 'gěi', 'give'),
  (2, 27, '送', 'sòng', 'send/give'),
  (2, 28, '到', 'dào', 'arrive'),
  (2, 29, '走', 'zǒu', 'walk'),
  (2, 30, '跑', 'pǎo', 'run'),
  (2, 31, '玩', 'wán', 'play'),
  (2, 32, '唱歌', 'chàng gē', 'sing'),
  (2, 33, '跳舞', 'tiào wǔ', 'dance'),
  (2, 34, '游泳', 'yóu yǒng', 'swim'),
  (2, 35, '运动', 'yùn dòng', 'exercise'),
  (2, 36, '旅游', 'lǚ yóu', 'travel'),
  (2, 37, '考试', 'kǎo shì', 'exam'),
  (2, 38, '问题', 'wèn tí', 'question'),
  (2, 39, '快', 'kuài', 'fast'),
  (2, 40, '慢', 'màn', 'slow'),
  (2, 41, '远', 'yuǎn', 'far'),
  (2, 42, '近', 'jìn', 'near'),
  (2, 43, '长', 'cháng', 'long'),
  (2, 44, '高', 'gāo', 'tall'),
  (2, 45, '新', 'xīn', 'new'),
  (2, 46, '旧', 'jiù', 'old'),
  (2, 47, '贵', 'guì', 'expensive'),
  (2, 48, '便宜', 'pián yi', 'cheap'),
  (2, 49, '容易', 'róng yì', 'easy'),
  (2, 50, '难', 'nán', 'difficult'),
  (2, 51, '重要', 'zhòng yào', 'important'),
  (2, 52, '生气', 'shēng qì', 'angry'),
  (2, 53, '难过', 'nán guò', 'sad'),
  (2, 54, '累', 'lèi', 'tired'),
  (2, 55, '忙', 'máng', 'busy'),
  (2, 56, '生病', 'shēng bìng', 'sick'),
  (2, 57, '身体', 'shēn tǐ', 'body'),
  (2, 58, '眼睛', 'yǎn jīng', 'eye'),
  (2, 59, '鼻子', 'bí zi', 'nose'),
  (2, 60, '耳朵', 'ěr duo', 'ear'),
  (2, 61, '哥哥', 'gē ge', 'older brother'),
  (2, 62, '弟弟', 'dì di', 'younger brother'),
  (2, 63, '姐姐', 'jiě jie', 'older sister'),
  (2, 64, '妹妹', 'mèi mei', 'younger sister'),
  (2, 65, '丈夫', 'zhàng fu', 'husband'),
  (2, 66, '妻子', 'qī zi', 'wife'),
  (2, 67, '孩子', 'hái zi', 'child'),
  (2, 68, '牛奶', 'niú nǎi', 'milk'),
  (2, 69, '鸡蛋', 'jī dàn', 'egg'),
  (2, 70, '面条', 'miàn tiáo', 'noodles'),
  (2, 71, '鱼', 'yú', 'fish'),
  (2, 72, '鸡', 'jī', 'chicken'),
  (2, 73, '咖啡', 'kā fēi', 'coffee'),
  (2, 74, '啤酒', 'pí jiǔ', 'beer'),
  (2, 75, '香蕉', 'xiāng jiāo', 'banana'),
  (2, 76, '西瓜', 'xī guā', 'watermelon'),
  (2, 77, '颜色', 'yán sè', 'color'),
  (2, 78, '红', 'hóng', 'red'),
  (2, 79, '白', 'bái', 'white'),
  (2, 80, '黑', 'hēi', 'black'),
  (2, 81, '路', 'lù', 'road'),
  (2, 82, '门', 'mén', 'door'),
  (2, 83, '窗户', 'chuāng hu', 'window'),
  (2, 84, '房间', 'fáng jiān', 'room'),
  (2, 85, '公司', 'gōng sī', 'company'),
  (2, 86, '教室', 'jiào shì', 'classroom'),
  (2, 87, '经常', 'jīng cháng', 'often'),
  (2, 88, '有时候', 'yǒu shí hou', 'sometimes'),
  (2, 89, '从不', 'cóng bù', 'never'),
  (2, 90, '总是', 'zǒng shì', 'always'),
  (2, 91, '突然', 'tū rán', 'suddenly'),
  (2, 92, '马上', 'mǎ shàng', 'immediately'),
  (2, 93, '一起', 'yī qǐ', 'together'),
  (2, 94, '还', 'hái', 'still'),
  (2, 95, '再', 'zài', 'again'),
  (2, 96, '又', 'yòu', 'again/also'),
  (2, 97, '最', 'zuì', 'most'),
  (2, 98, '只', 'zhǐ', 'only'),
  (2, 99, '刚才', 'gāng cái', 'just now'),
  (2, 100, '正在', 'zhèng zài', 'in the process of'),
  (2, 101, '让', 'ràng', 'let/allow'),
  (2, 102, '从', 'cóng', 'from'),
  (2, 103, '向', 'xiàng', 'toward'),
  (2, 104, '离', 'lí', 'from/away'),
  (2, 105, '往', 'wǎng', 'toward'),
  (2, 106, '为了', 'wèi le', 'in order to'),
  (2, 107, '对', 'duì', 'toward/to'),
  (2, 108, '比', 'bǐ', 'compare'),
  (2, 109, '把', 'bǎ', 'object marker'),
  (2, 110, '被', 'bèi', 'passive marker'),
  (2, 111, '着', 'zhe', 'continuous aspect'),
  (2, 112, '过', 'guò', 'experiential aspect'),
  (2, 113, '得', 'de', 'complement marker'),
  (2, 114, '地', 'de', 'adverbial marker'),
  (2, 115, '哦', 'ò', 'oh'),
  (2, 116, '吧', 'ba', 'suggestion particle'),
  (2, 117, '啊', 'a', 'exclamation particle'),
  (2, 118, '千', 'qiān', 'thousand'),
  (2, 119, '万', 'wàn', 'ten thousand'),
  (2, 120, '两', 'liǎng', 'two (with MW)'),
  (2, 121, '第', 'dì', 'ordinal prefix'),
  (2, 122, '每', 'měi', 'every'),
  (2, 123, '层', 'céng', 'floor/layer'),
  (2, 124, '次', 'cì', 'time (occurrence)'),
  (2, 125, '双', 'shuāng', 'pair'),
  (2, 126, '件', 'jiàn', 'MW for clothes'),
  (2, 127, '条', 'tiáo', 'MW for long things'),
  (2, 128, '张', 'zhāng', 'MW for flat things'),
  (2, 129, '公共汽车', 'gōng gòng qì chē', 'bus'),
  (2, 130, '自行车', 'zì xíng chē', 'bicycle'),
  (2, 131, '地铁', 'dì tiě', 'subway'),
  (2, 132, '船', 'chuán', 'boat'),
  (2, 133, '手表', 'shǒu biǎo', 'watch'),
  (2, 134, '眼镜', 'yǎn jìng', 'glasses'),
  (2, 135, '报纸', 'bào zhǐ', 'newspaper'),
  (2, 136, '地图', 'dì tú', 'map'),
  (2, 137, '药', 'yào', 'medicine'),
  (2, 138, '花', 'huā', 'flower'),
  (2, 139, '树', 'shù', 'tree'),
  (2, 140, '雪', 'xuě', 'snow'),
  (2, 141, '风', 'fēng', 'wind'),
  (2, 142, '阴', 'yīn', 'cloudy'),
  (2, 143, '晴', 'qíng', 'sunny'),
  (2, 144, '春', 'chūn', 'spring'),
  (2, 145, '秋', 'qiū', 'autumn'),
  (2, 146, '右边', 'yòu biān', 'right side'),
  (2, 147, '左边', 'zuǒ biān', 'left side'),
  (2, 148, '旁边', 'páng biān', 'beside'),
  (2, 149, '外面', 'wài miàn', 'outside'),
  (2, 150, '附近', 'fù jìn', 'nearby')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

-- =====================================================
-- HSK 3 — Intermediate (300 words)
-- =====================================================
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (3, 1, '决定', 'jué dìng', 'decide'),
  (3, 2, '变化', 'biàn huà', 'change'),
  (3, 3, '经验', 'jīng yàn', 'experience'),
  (3, 4, '机会', 'jī huì', 'opportunity'),
  (3, 5, '成功', 'chéng gōng', 'success'),
  (3, 6, '历史', 'lì shǐ', 'history'),
  (3, 7, '文化', 'wén huà', 'culture'),
  (3, 8, '音乐', 'yīn yuè', 'music'),
  (3, 9, '比赛', 'bǐ sài', 'competition'),
  (3, 10, '地方', 'dì fang', 'place'),
  (3, 11, '环境', 'huán jìng', 'environment'),
  (3, 12, '世界', 'shì jiè', 'world'),
  (3, 13, '社会', 'shè huì', 'society'),
  (3, 14, '经济', 'jīng jì', 'economy'),
  (3, 15, '城市', 'chéng shì', 'city'),
  (3, 16, '国家', 'guó jiā', 'country'),
  (3, 17, '语言', 'yǔ yán', 'language'),
  (3, 18, '新闻', 'xīn wén', 'news'),
  (3, 19, '健康', 'jiàn kāng', 'healthy'),
  (3, 20, '安全', 'ān quán', 'safe'),
  (3, 21, '方便', 'fāng biàn', 'convenient'),
  (3, 22, '简单', 'jiǎn dān', 'simple'),
  (3, 23, '复杂', 'fù zá', 'complex'),
  (3, 24, '特别', 'tè bié', 'special'),
  (3, 25, '普通', 'pǔ tōng', 'ordinary'),
  (3, 26, '认真', 'rèn zhēn', 'serious'),
  (3, 27, '紧张', 'jǐn zhāng', 'nervous'),
  (3, 28, '害怕', 'hài pà', 'afraid'),
  (3, 29, '担心', 'dān xīn', 'worry'),
  (3, 30, '满意', 'mǎn yì', 'satisfied'),
  (3, 31, '失望', 'shī wàng', 'disappointed'),
  (3, 32, '感兴趣', 'gǎn xìng qù', 'interested'),
  (3, 33, '选择', 'xuǎn zé', 'choose'),
  (3, 34, '同意', 'tóng yì', 'agree'),
  (3, 35, '拒绝', 'jù jué', 'refuse'),
  (3, 36, '接受', 'jiē shòu', 'accept'),
  (3, 37, '解释', 'jiě shì', 'explain'),
  (3, 38, '讨论', 'tǎo lùn', 'discuss'),
  (3, 39, '注意', 'zhù yì', 'attention'),
  (3, 40, '影响', 'yǐng xiǎng', 'influence'),
  (3, 41, '保护', 'bǎo hù', 'protect'),
  (3, 42, '提高', 'tí gāo', 'improve'),
  (3, 43, '发展', 'fā zhǎn', 'develop'),
  (3, 44, '解决', 'jiě jué', 'solve'),
  (3, 45, '表示', 'biǎo shì', 'express'),
  (3, 46, '参加', 'cān jiā', 'participate'),
  (3, 47, '离开', 'lí kāi', 'leave'),
  (3, 48, '关心', 'guān xīn', 'care about'),
  (3, 49, '照顾', 'zhào gù', 'take care of'),
  (3, 50, '习惯', 'xí guàn', 'habit'),
  (3, 51, '练习', 'liàn xí', 'practice'),
  (3, 52, '努力', 'nǔ lì', 'effort'),
  (3, 53, '关系', 'guān xi', 'relationship'),
  (3, 54, '办法', 'bàn fǎ', 'method'),
  (3, 55, '原因', 'yuán yīn', 'reason'),
  (3, 56, '结果', 'jié guǒ', 'result'),
  (3, 57, '条件', 'tiáo jiàn', 'condition'),
  (3, 58, '计划', 'jì huà', 'plan'),
  (3, 59, '春天', 'chūn tiān', 'spring'),
  (3, 60, '夏天', 'xià tiān', 'summer'),
  (3, 61, '秋天', 'qiū tiān', 'autumn'),
  (3, 62, '冬天', 'dōng tiān', 'winter'),
  (3, 63, '太阳', 'tài yáng', 'sun'),
  (3, 64, '月亮', 'yuè liang', 'moon'),
  (3, 65, '地图', 'dì tú', 'map'),
  (3, 66, '照片', 'zhào piàn', 'photo'),
  (3, 67, '礼物', 'lǐ wù', 'gift'),
  (3, 68, '节日', 'jié rì', 'holiday'),
  (3, 69, '生日', 'shēng rì', 'birthday'),
  (3, 70, '邻居', 'lín jū', 'neighbor'),
  (3, 71, '客人', 'kè rén', 'guest'),
  (3, 72, '同事', 'tóng shì', 'colleague'),
  (3, 73, '校长', 'xiào zhǎng', 'principal'),
  (3, 74, '教授', 'jiào shòu', 'professor'),
  (3, 75, '作者', 'zuò zhě', 'author'),
  (3, 76, '观众', 'guān zhòng', 'audience'),
  (3, 77, '顾客', 'gù kè', 'customer'),
  (3, 78, '乘客', 'chéng kè', 'passenger'),
  (3, 79, '数学', 'shù xué', 'mathematics'),
  (3, 80, '科学', 'kē xué', 'science'),
  (3, 81, '技术', 'jì shù', 'technology'),
  (3, 82, '网站', 'wǎng zhàn', 'website'),
  (3, 83, '网络', 'wǎng luò', 'network/internet'),
  (3, 84, '信息', 'xìn xī', 'information'),
  (3, 85, '材料', 'cái liào', 'material'),
  (3, 86, '工具', 'gōng jù', 'tool'),
  (3, 87, '机器', 'jī qì', 'machine'),
  (3, 88, '规定', 'guī dìng', 'regulation'),
  (3, 89, '法律', 'fǎ lǜ', 'law'),
  (3, 90, '政治', 'zhèng zhì', 'politics'),
  (3, 91, '民族', 'mín zú', 'nationality/ethnic'),
  (3, 92, '传统', 'chuán tǒng', 'tradition'),
  (3, 93, '活动', 'huó dòng', 'activity'),
  (3, 94, '节目', 'jié mù', 'program/show'),
  (3, 95, '广告', 'guǎng gào', 'advertisement'),
  (3, 96, '文章', 'wén zhāng', 'article'),
  (3, 97, '故事', 'gù shì', 'story'),
  (3, 98, '笑话', 'xiào hua', 'joke'),
  (3, 99, '理想', 'lǐ xiǎng', 'ideal'),
  (3, 100, '梦想', 'mèng xiǎng', 'dream'),
  (3, 101, '目的', 'mù dì', 'purpose'),
  (3, 102, '意见', 'yì jiàn', 'opinion'),
  (3, 103, '态度', 'tài dù', 'attitude'),
  (3, 104, '感觉', 'gǎn jué', 'feeling'),
  (3, 105, '印象', 'yìn xiàng', 'impression'),
  (3, 106, '记忆', 'jì yì', 'memory'),
  (3, 107, '知识', 'zhī shi', 'knowledge'),
  (3, 108, '能力', 'néng lì', 'ability'),
  (3, 109, '水平', 'shuǐ píng', 'level'),
  (3, 110, '成绩', 'chéng jì', 'grade/result'),
  (3, 111, '进步', 'jìn bù', 'progress'),
  (3, 112, '错误', 'cuò wù', 'mistake'),
  (3, 113, '经过', 'jīng guò', 'pass through'),
  (3, 114, '适应', 'shì yìng', 'adapt'),
  (3, 115, '发现', 'fā xiàn', 'discover'),
  (3, 116, '研究', 'yán jiū', 'research'),
  (3, 117, '调查', 'diào chá', 'investigate'),
  (3, 118, '检查', 'jiǎn chá', 'examine'),
  (3, 119, '比较', 'bǐ jiào', 'compare'),
  (3, 120, '区别', 'qū bié', 'difference'),
  (3, 121, '联系', 'lián xì', 'contact'),
  (3, 122, '交流', 'jiāo liú', 'exchange'),
  (3, 123, '翻译', 'fān yì', 'translate'),
  (3, 124, '理解', 'lǐ jiě', 'understand'),
  (3, 125, '表达', 'biǎo dá', 'express'),
  (3, 126, '感谢', 'gǎn xiè', 'thank'),
  (3, 127, '道歉', 'dào qiàn', 'apologize'),
  (3, 128, '赞成', 'zàn chéng', 'approve'),
  (3, 129, '反对', 'fǎn duì', 'oppose'),
  (3, 130, '建议', 'jiàn yì', 'suggest'),
  (3, 131, '提供', 'tí gōng', 'provide'),
  (3, 132, '支持', 'zhī chí', 'support'),
  (3, 133, '鼓励', 'gǔ lì', 'encourage'),
  (3, 134, '批评', 'pī píng', 'criticize'),
  (3, 135, '表扬', 'biǎo yáng', 'praise'),
  (3, 136, '尊重', 'zūn zhòng', 'respect'),
  (3, 137, '信任', 'xìn rèn', 'trust'),
  (3, 138, '竞争', 'jìng zhēng', 'compete'),
  (3, 139, '合作', 'hé zuò', 'cooperate'),
  (3, 140, '交通', 'jiāo tōng', 'traffic'),
  (3, 141, '距离', 'jù lí', 'distance'),
  (3, 142, '速度', 'sù dù', 'speed'),
  (3, 143, '方向', 'fāng xiàng', 'direction'),
  (3, 144, '位置', 'wèi zhì', 'position'),
  (3, 145, '空气', 'kōng qì', 'air'),
  (3, 146, '温度', 'wēn dù', 'temperature'),
  (3, 147, '自然', 'zì rán', 'nature'),
  (3, 148, '动物', 'dòng wù', 'animal'),
  (3, 149, '植物', 'zhí wù', 'plant'),
  (3, 150, '森林', 'sēn lín', 'forest'),
  (3, 151, '海洋', 'hǎi yáng', 'ocean'),
  (3, 152, '河', 'hé', 'river'),
  (3, 153, '山', 'shān', 'mountain'),
  (3, 154, '地球', 'dì qiú', 'earth'),
  (3, 155, '星星', 'xīng xing', 'star'),
  (3, 156, '银行', 'yín háng', 'bank'),
  (3, 157, '超市', 'chāo shì', 'supermarket'),
  (3, 158, '图书馆', 'tú shū guǎn', 'library'),
  (3, 159, '博物馆', 'bó wù guǎn', 'museum'),
  (3, 160, '体育馆', 'tǐ yù guǎn', 'gymnasium'),
  (3, 161, '公园', 'gōng yuán', 'park'),
  (3, 162, '广场', 'guǎng chǎng', 'square/plaza'),
  (3, 163, '市场', 'shì chǎng', 'market'),
  (3, 164, '厨房', 'chú fáng', 'kitchen'),
  (3, 165, '卫生间', 'wèi shēng jiān', 'bathroom'),
  (3, 166, '阳台', 'yáng tái', 'balcony'),
  (3, 167, '楼', 'lóu', 'building/floor'),
  (3, 168, '电梯', 'diàn tī', 'elevator'),
  (3, 169, '钥匙', 'yào shi', 'key'),
  (3, 170, '行李', 'xíng li', 'luggage'),
  (3, 171, '护照', 'hù zhào', 'passport'),
  (3, 172, '签证', 'qiān zhèng', 'visa'),
  (3, 173, '日记', 'rì jì', 'diary'),
  (3, 174, '信', 'xìn', 'letter'),
  (3, 175, '信封', 'xìn fēng', 'envelope'),
  (3, 176, '词典', 'cí diǎn', 'dictionary'),
  (3, 177, '作业', 'zuò yè', 'homework'),
  (3, 178, '课文', 'kè wén', 'text/lesson'),
  (3, 179, '语法', 'yǔ fǎ', 'grammar'),
  (3, 180, '句子', 'jù zi', 'sentence'),
  (3, 181, '段落', 'duàn luò', 'paragraph'),
  (3, 182, '页', 'yè', 'page'),
  (3, 183, '安排', 'ān pái', 'arrange'),
  (3, 184, '组织', 'zǔ zhī', 'organize'),
  (3, 185, '管理', 'guǎn lǐ', 'manage'),
  (3, 186, '负责', 'fù zé', 'responsible'),
  (3, 187, '完全', 'wán quán', 'completely'),
  (3, 188, '基本', 'jī běn', 'basic'),
  (3, 189, '主要', 'zhǔ yào', 'main'),
  (3, 190, '具体', 'jù tǐ', 'specific'),
  (3, 191, '实际', 'shí jì', 'actual'),
  (3, 192, '正常', 'zhèng cháng', 'normal'),
  (3, 193, '合适', 'hé shì', 'suitable'),
  (3, 194, '丰富', 'fēng fù', 'rich/abundant'),
  (3, 195, '深', 'shēn', 'deep'),
  (3, 196, '浅', 'qiǎn', 'shallow'),
  (3, 197, '厚', 'hòu', 'thick'),
  (3, 198, '薄', 'báo', 'thin'),
  (3, 199, '宽', 'kuān', 'wide'),
  (3, 200, '窄', 'zhǎi', 'narrow'),
  (3, 201, '轻', 'qīng', 'light'),
  (3, 202, '重', 'zhòng', 'heavy'),
  (3, 203, '软', 'ruǎn', 'soft'),
  (3, 204, '硬', 'yìng', 'hard'),
  (3, 205, '干净', 'gān jìng', 'clean'),
  (3, 206, '脏', 'zāng', 'dirty'),
  (3, 207, '整齐', 'zhěng qí', 'tidy'),
  (3, 208, '乱', 'luàn', 'messy'),
  (3, 209, '聪明', 'cōng ming', 'smart'),
  (3, 210, '笨', 'bèn', 'stupid'),
  (3, 211, '勤劳', 'qín láo', 'hardworking'),
  (3, 212, '懒', 'lǎn', 'lazy'),
  (3, 213, '诚实', 'chéng shí', 'honest'),
  (3, 214, '勇敢', 'yǒng gǎn', 'brave'),
  (3, 215, '温柔', 'wēn róu', 'gentle'),
  (3, 216, '活泼', 'huó po', 'lively'),
  (3, 217, '严肃', 'yán sù', 'serious/solemn'),
  (3, 218, '幽默', 'yōu mò', 'humorous'),
  (3, 219, '热情', 'rè qíng', 'enthusiastic'),
  (3, 220, '冷静', 'lěng jìng', 'calm'),
  (3, 221, '耐心', 'nài xīn', 'patient'),
  (3, 222, '骄傲', 'jiāo ào', 'proud'),
  (3, 223, '谦虚', 'qiān xū', 'modest'),
  (3, 224, '自信', 'zì xìn', 'confident'),
  (3, 225, '害羞', 'hài xiū', 'shy'),
  (3, 226, '独立', 'dú lì', 'independent'),
  (3, 227, '保持', 'bǎo chí', 'maintain'),
  (3, 228, '继续', 'jì xù', 'continue'),
  (3, 229, '坚持', 'jiān chí', 'persist'),
  (3, 230, '放弃', 'fàng qì', 'give up'),
  (3, 231, '克服', 'kè fú', 'overcome'),
  (3, 232, '接触', 'jiē chù', 'contact'),
  (3, 233, '引起', 'yǐn qǐ', 'cause'),
  (3, 234, '产生', 'chǎn shēng', 'produce'),
  (3, 235, '代替', 'dài tì', 'replace'),
  (3, 236, '包括', 'bāo kuò', 'include'),
  (3, 237, '属于', 'shǔ yú', 'belong to'),
  (3, 238, '缺少', 'quē shǎo', 'lack'),
  (3, 239, '增加', 'zēng jiā', 'increase'),
  (3, 240, '减少', 'jiǎn shǎo', 'reduce'),
  (3, 241, '扩大', 'kuò dà', 'expand'),
  (3, 242, '缩小', 'suō xiǎo', 'shrink'),
  (3, 243, '改善', 'gǎi shàn', 'improve'),
  (3, 244, '推迟', 'tuī chí', 'postpone'),
  (3, 245, '取消', 'qǔ xiāo', 'cancel'),
  (3, 246, '恢复', 'huī fù', 'recover'),
  (3, 247, '打扫', 'dǎ sǎo', 'clean/sweep'),
  (3, 248, '整理', 'zhěng lǐ', 'organize/tidy'),
  (3, 249, '修理', 'xiū lǐ', 'repair'),
  (3, 250, '打印', 'dǎ yìn', 'print'),
  (3, 251, '复印', 'fù yìn', 'photocopy'),
  (3, 252, '下载', 'xià zǎi', 'download'),
  (3, 253, '上传', 'shàng chuán', 'upload'),
  (3, 254, '登录', 'dēng lù', 'log in'),
  (3, 255, '搜索', 'sōu suǒ', 'search'),
  (3, 256, '短信', 'duǎn xìn', 'text message'),
  (3, 257, '密码', 'mì mǎ', 'password'),
  (3, 258, '申请', 'shēn qǐng', 'apply'),
  (3, 259, '批准', 'pī zhǔn', 'approve'),
  (3, 260, '证明', 'zhèng míng', 'prove'),
  (3, 261, '通知', 'tōng zhī', 'notify'),
  (3, 262, '邀请', 'yāo qǐng', 'invite'),
  (3, 263, '约', 'yuē', 'make appointment'),
  (3, 264, '拜访', 'bài fǎng', 'visit'),
  (3, 265, '招待', 'zhāo dài', 'entertain'),
  (3, 266, '享受', 'xiǎng shòu', 'enjoy'),
  (3, 267, '庆祝', 'qìng zhù', 'celebrate'),
  (3, 268, '祝贺', 'zhù hè', 'congratulate'),
  (3, 269, '鼓掌', 'gǔ zhǎng', 'applaud'),
  (3, 270, '散步', 'sàn bù', 'take a walk'),
  (3, 271, '爬山', 'pá shān', 'climb mountain'),
  (3, 272, '购物', 'gòu wù', 'shopping'),
  (3, 273, '逛街', 'guàng jiē', 'window shopping'),
  (3, 274, '打折', 'dǎ zhé', 'discount'),
  (3, 275, '付款', 'fù kuǎn', 'pay'),
  (3, 276, '找零', 'zhǎo líng', 'give change'),
  (3, 277, '预订', 'yù dìng', 'reserve'),
  (3, 278, '退', 'tuì', 'return/retreat'),
  (3, 279, '换', 'huàn', 'exchange'),
  (3, 280, '收', 'shōu', 'receive'),
  (3, 281, '寄', 'jì', 'mail/send'),
  (3, 282, '接', 'jiē', 'pick up/receive'),
  (3, 283, '挂', 'guà', 'hang'),
  (3, 284, '放', 'fàng', 'put/place'),
  (3, 285, '拿', 'ná', 'take/hold'),
  (3, 286, '搬', 'bān', 'move'),
  (3, 287, '推', 'tuī', 'push'),
  (3, 288, '拉', 'lā', 'pull'),
  (3, 289, '举', 'jǔ', 'raise/lift'),
  (3, 290, '扔', 'rēng', 'throw'),
  (3, 291, '弄', 'nòng', 'do/handle'),
  (3, 292, '获得', 'huò dé', 'obtain'),
  (3, 293, '实现', 'shí xiàn', 'realize'),
  (3, 294, '完善', 'wán shàn', 'improve/perfect'),
  (3, 295, '培养', 'péi yǎng', 'cultivate'),
  (3, 296, '教育', 'jiào yù', 'education'),
  (3, 297, '毕业', 'bì yè', 'graduate'),
  (3, 298, '专业', 'zhuān yè', 'major/profession'),
  (3, 299, '职业', 'zhí yè', 'career'),
  (3, 300, '经历', 'jīng lì', 'experience')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;
