-- =====================================================
-- FLASHQI SEED DATA
-- Run this in Supabase SQL Editor AFTER running supabase-schema.sql
-- =====================================================

-- =====================================================
-- HSK 1 (148 words)
-- =====================================================
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (1, 1, '你好', 'nǐ hǎo', 'hello'),
  (1, 2, '谢谢', 'xiè xie', 'thank you'),
  (1, 3, '再见', 'zài jiàn', 'goodbye'),
  (1, 4, '对不起', 'duì bu qǐ', 'sorry'),
  (1, 5, '是', 'shì', 'yes/to be'),
  (1, 6, '不', 'bù', 'no/not'),
  (1, 7, '我', 'wǒ', 'I/me'),
  (1, 8, '你', 'nǐ', 'you'),
  (1, 9, '他', 'tā', 'he/him'),
  (1, 10, '她', 'tā', 'she/her'),
  (1, 11, '们', 'men', 'plural marker'),
  (1, 12, '这', 'zhè', 'this'),
  (1, 13, '那', 'nà', 'that'),
  (1, 14, '什么', 'shén me', 'what'),
  (1, 15, '谁', 'shuí', 'who'),
  (1, 16, '哪', 'nǎ', 'which/where'),
  (1, 17, '多少', 'duō shao', 'how many'),
  (1, 18, '几', 'jǐ', 'how many/several'),
  (1, 19, '怎么', 'zěn me', 'how'),
  (1, 20, '怎么样', 'zěn me yàng', 'how about'),
  (1, 21, '一', 'yī', 'one'),
  (1, 22, '二', 'èr', 'two'),
  (1, 23, '三', 'sān', 'three'),
  (1, 24, '四', 'sì', 'four'),
  (1, 25, '五', 'wǔ', 'five'),
  (1, 26, '六', 'liù', 'six'),
  (1, 27, '七', 'qī', 'seven'),
  (1, 28, '八', 'bā', 'eight'),
  (1, 29, '九', 'jiǔ', 'nine'),
  (1, 30, '十', 'shí', 'ten'),
  (1, 31, '零', 'líng', 'zero'),
  (1, 32, '百', 'bǎi', 'hundred'),
  (1, 33, '爸爸', 'bà ba', 'father'),
  (1, 34, '妈妈', 'mā ma', 'mother'),
  (1, 35, '儿子', 'ér zi', 'son'),
  (1, 36, '女儿', 'nǚ ér', 'daughter'),
  (1, 37, '老师', 'lǎo shī', 'teacher'),
  (1, 38, '学生', 'xué shēng', 'student'),
  (1, 39, '朋友', 'péng you', 'friend'),
  (1, 40, '医生', 'yī shēng', 'doctor'),
  (1, 41, '人', 'rén', 'person'),
  (1, 42, '大', 'dà', 'big'),
  (1, 43, '小', 'xiǎo', 'small'),
  (1, 44, '多', 'duō', 'many'),
  (1, 45, '少', 'shǎo', 'few'),
  (1, 46, '好', 'hǎo', 'good'),
  (1, 47, '高兴', 'gāo xìng', 'happy'),
  (1, 48, '冷', 'lěng', 'cold'),
  (1, 49, '热', 'rè', 'hot'),
  (1, 50, '漂亮', 'piào liang', 'beautiful'),
  (1, 51, '吃', 'chī', 'eat'),
  (1, 52, '喝', 'hē', 'drink'),
  (1, 53, '去', 'qù', 'go'),
  (1, 54, '来', 'lái', 'come'),
  (1, 55, '看', 'kàn', 'look/see'),
  (1, 56, '听', 'tīng', 'listen'),
  (1, 57, '说', 'shuō', 'speak'),
  (1, 58, '读', 'dú', 'read'),
  (1, 59, '写', 'xiě', 'write'),
  (1, 60, '学', 'xué', 'learn'),
  (1, 61, '工作', 'gōng zuò', 'work'),
  (1, 62, '住', 'zhù', 'live'),
  (1, 63, '买', 'mǎi', 'buy'),
  (1, 64, '开', 'kāi', 'open'),
  (1, 65, '坐', 'zuò', 'sit'),
  (1, 66, '叫', 'jiào', 'call/named'),
  (1, 67, '爱', 'ài', 'love'),
  (1, 68, '想', 'xiǎng', 'think/want'),
  (1, 69, '认识', 'rèn shi', 'know (person)'),
  (1, 70, '会', 'huì', 'can/will'),
  (1, 71, '能', 'néng', 'can/able'),
  (1, 72, '有', 'yǒu', 'have'),
  (1, 73, '在', 'zài', 'at/in'),
  (1, 74, '做', 'zuò', 'do/make'),
  (1, 75, '睡觉', 'shuì jiào', 'sleep'),
  (1, 76, '水', 'shuǐ', 'water'),
  (1, 77, '茶', 'chá', 'tea'),
  (1, 78, '米饭', 'mǐ fàn', 'rice'),
  (1, 79, '水果', 'shuǐ guǒ', 'fruit'),
  (1, 80, '苹果', 'píng guǒ', 'apple'),
  (1, 81, '菜', 'cài', 'dish/vegetable'),
  (1, 82, '猫', 'māo', 'cat'),
  (1, 83, '狗', 'gǒu', 'dog'),
  (1, 84, '书', 'shū', 'book'),
  (1, 85, '电脑', 'diàn nǎo', 'computer'),
  (1, 86, '电视', 'diàn shì', 'TV'),
  (1, 87, '电影', 'diàn yǐng', 'movie'),
  (1, 88, '手机', 'shǒu jī', 'phone'),
  (1, 89, '钱', 'qián', 'money'),
  (1, 90, '飞机', 'fēi jī', 'airplane'),
  (1, 91, '出租车', 'chū zū chē', 'taxi'),
  (1, 92, '车', 'chē', 'car'),
  (1, 93, '学校', 'xué xiào', 'school'),
  (1, 94, '医院', 'yī yuàn', 'hospital'),
  (1, 95, '商店', 'shāng diàn', 'store'),
  (1, 96, '饭馆', 'fàn guǎn', 'restaurant'),
  (1, 97, '家', 'jiā', 'home'),
  (1, 98, '中国', 'zhōng guó', 'China'),
  (1, 99, '北京', 'Běi jīng', 'Beijing'),
  (1, 100, '天气', 'tiān qì', 'weather'),
  (1, 101, '下雨', 'xià yǔ', 'rain'),
  (1, 102, '今天', 'jīn tiān', 'today'),
  (1, 103, '明天', 'míng tiān', 'tomorrow'),
  (1, 104, '昨天', 'zuó tiān', 'yesterday'),
  (1, 105, '现在', 'xiàn zài', 'now'),
  (1, 106, '时候', 'shí hou', 'time/moment'),
  (1, 107, '年', 'nián', 'year'),
  (1, 108, '月', 'yuè', 'month'),
  (1, 109, '日', 'rì', 'day'),
  (1, 110, '星期', 'xīng qī', 'week'),
  (1, 111, '点', 'diǎn', 'o''clock'),
  (1, 112, '分钟', 'fēn zhōng', 'minute'),
  (1, 113, '前面', 'qián miàn', 'front'),
  (1, 114, '后面', 'hòu miàn', 'back/behind'),
  (1, 115, '里面', 'lǐ miàn', 'inside'),
  (1, 116, '上', 'shàng', 'up/on'),
  (1, 117, '下', 'xià', 'down/under'),
  (1, 118, '很', 'hěn', 'very'),
  (1, 119, '也', 'yě', 'also'),
  (1, 120, '都', 'dōu', 'all'),
  (1, 121, '没', 'méi', 'not/no'),
  (1, 122, '和', 'hé', 'and'),
  (1, 123, '的', 'de', 'possessive particle'),
  (1, 124, '了', 'le', 'completed action'),
  (1, 125, '吗', 'ma', 'question particle'),
  (1, 126, '呢', 'ne', 'modal particle'),
  (1, 127, '个', 'gè', 'measure word'),
  (1, 128, '岁', 'suì', 'years old'),
  (1, 129, '块', 'kuài', 'yuan/piece'),
  (1, 130, '本', 'běn', 'MW for books'),
  (1, 131, '些', 'xiē', 'some'),
  (1, 132, '请', 'qǐng', 'please'),
  (1, 133, '太', 'tài', 'too (much)'),
  (1, 134, '对', 'duì', 'correct'),
  (1, 135, '名字', 'míng zi', 'name'),
  (1, 136, '衣服', 'yī fu', 'clothes'),
  (1, 137, '杯子', 'bēi zi', 'cup'),
  (1, 138, '桌子', 'zhuō zi', 'table'),
  (1, 139, '椅子', 'yǐ zi', 'chair'),
  (1, 140, '东西', 'dōng xi', 'thing'),
  (1, 141, '字', 'zì', 'character'),
  (1, 142, '汉语', 'hàn yǔ', 'Chinese language'),
  (1, 143, '中午', 'zhōng wǔ', 'noon'),
  (1, 144, '早上', 'zǎo shang', 'morning'),
  (1, 145, '下午', 'xià wǔ', 'afternoon'),
  (1, 146, '晚上', 'wǎn shang', 'evening'),
  (1, 147, '小姐', 'xiǎo jiě', 'miss'),
  (1, 148, '先生', 'xiān sheng', 'mister')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

-- =====================================================
-- HSK 2 (100 words)
-- =====================================================
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (2, 1, '因为', 'yīn wèi', 'because'),
  (2, 2, '所以', 'suǒ yǐ', 'so/therefore'),
  (2, 3, '但是', 'dàn shì', 'but'),
  (2, 4, '虽然', 'suī rán', 'although'),
  (2, 5, '如果', 'rú guǒ', 'if'),
  (2, 6, '已经', 'yǐ jīng', 'already'),
  (2, 7, '可以', 'kě yǐ', 'can/may'),
  (2, 8, '可能', 'kě néng', 'possible'),
  (2, 9, '需要', 'xū yào', 'need'),
  (2, 10, '应该', 'yīng gāi', 'should'),
  (2, 11, '必须', 'bì xū', 'must'),
  (2, 12, '知道', 'zhī dào', 'know'),
  (2, 13, '觉得', 'jué de', 'feel/think'),
  (2, 14, '希望', 'xī wàng', 'hope'),
  (2, 15, '相信', 'xiāng xìn', 'believe'),
  (2, 16, '帮助', 'bāng zhù', 'help'),
  (2, 17, '准备', 'zhǔn bèi', 'prepare'),
  (2, 18, '开始', 'kāi shǐ', 'begin'),
  (2, 19, '完成', 'wán chéng', 'finish'),
  (2, 20, '问', 'wèn', 'ask'),
  (2, 21, '回答', 'huí dá', 'answer'),
  (2, 22, '告诉', 'gào su', 'tell'),
  (2, 23, '介绍', 'jiè shào', 'introduce'),
  (2, 24, '等', 'děng', 'wait'),
  (2, 25, '找', 'zhǎo', 'find/look for'),
  (2, 26, '给', 'gěi', 'give'),
  (2, 27, '送', 'sòng', 'send/give'),
  (2, 28, '到', 'dào', 'arrive'),
  (2, 29, '走', 'zǒu', 'walk'),
  (2, 30, '跑', 'pǎo', 'run'),
  (2, 31, '玩', 'wán', 'play'),
  (2, 32, '唱歌', 'chàng gē', 'sing'),
  (2, 33, '跳舞', 'tiào wǔ', 'dance'),
  (2, 34, '游泳', 'yóu yǒng', 'swim'),
  (2, 35, '运动', 'yùn dòng', 'exercise'),
  (2, 36, '旅游', 'lǚ yóu', 'travel'),
  (2, 37, '考试', 'kǎo shì', 'exam'),
  (2, 38, '问题', 'wèn tí', 'question'),
  (2, 39, '快', 'kuài', 'fast'),
  (2, 40, '慢', 'màn', 'slow'),
  (2, 41, '远', 'yuǎn', 'far'),
  (2, 42, '近', 'jìn', 'near'),
  (2, 43, '长', 'cháng', 'long'),
  (2, 44, '高', 'gāo', 'tall'),
  (2, 45, '新', 'xīn', 'new'),
  (2, 46, '旧', 'jiù', 'old'),
  (2, 47, '贵', 'guì', 'expensive'),
  (2, 48, '便宜', 'pián yi', 'cheap'),
  (2, 49, '容易', 'róng yì', 'easy'),
  (2, 50, '难', 'nán', 'difficult'),
  (2, 51, '重要', 'zhòng yào', 'important'),
  (2, 52, '生气', 'shēng qì', 'angry'),
  (2, 53, '难过', 'nán guò', 'sad'),
  (2, 54, '累', 'lèi', 'tired'),
  (2, 55, '忙', 'máng', 'busy'),
  (2, 56, '生病', 'shēng bìng', 'sick'),
  (2, 57, '身体', 'shēn tǐ', 'body'),
  (2, 58, '眼睛', 'yǎn jīng', 'eye'),
  (2, 59, '鼻子', 'bí zi', 'nose'),
  (2, 60, '耳朵', 'ěr duo', 'ear'),
  (2, 61, '哥哥', 'gē ge', 'older brother'),
  (2, 62, '弟弟', 'dì di', 'younger brother'),
  (2, 63, '姐姐', 'jiě jie', 'older sister'),
  (2, 64, '妹妹', 'mèi mei', 'younger sister'),
  (2, 65, '丈夫', 'zhàng fu', 'husband'),
  (2, 66, '妻子', 'qī zi', 'wife'),
  (2, 67, '孩子', 'hái zi', 'child'),
  (2, 68, '牛奶', 'niú nǎi', 'milk'),
  (2, 69, '鸡蛋', 'jī dàn', 'egg'),
  (2, 70, '面条', 'miàn tiáo', 'noodles'),
  (2, 71, '鱼', 'yú', 'fish'),
  (2, 72, '鸡', 'jī', 'chicken'),
  (2, 73, '咖啡', 'kā fēi', 'coffee'),
  (2, 74, '啤酒', 'pí jiǔ', 'beer'),
  (2, 75, '香蕉', 'xiāng jiāo', 'banana'),
  (2, 76, '西瓜', 'xī guā', 'watermelon'),
  (2, 77, '颜色', 'yán sè', 'color'),
  (2, 78, '红', 'hóng', 'red'),
  (2, 79, '白', 'bái', 'white'),
  (2, 80, '黑', 'hēi', 'black'),
  (2, 81, '路', 'lù', 'road'),
  (2, 82, '门', 'mén', 'door'),
  (2, 83, '窗户', 'chuāng hu', 'window'),
  (2, 84, '房间', 'fáng jiān', 'room'),
  (2, 85, '公司', 'gōng sī', 'company'),
  (2, 86, '教室', 'jiào shì', 'classroom'),
  (2, 87, '经常', 'jīng cháng', 'often'),
  (2, 88, '有时候', 'yǒu shí hou', 'sometimes'),
  (2, 89, '从不', 'cóng bù', 'never'),
  (2, 90, '总是', 'zǒng shì', 'always'),
  (2, 91, '突然', 'tū rán', 'suddenly'),
  (2, 92, '马上', 'mǎ shàng', 'immediately'),
  (2, 93, '一起', 'yī qǐ', 'together'),
  (2, 94, '还', 'hái', 'still'),
  (2, 95, '再', 'zài', 'again'),
  (2, 96, '又', 'yòu', 'again/also'),
  (2, 97, '最', 'zuì', 'most'),
  (2, 98, '只', 'zhǐ', 'only'),
  (2, 99, '刚才', 'gāng cái', 'just now'),
  (2, 100, '正在', 'zhèng zài', 'in the process of')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

-- =====================================================
-- HSK 3 (70 words)
-- =====================================================
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (3, 1, '决定', 'jué dìng', 'decide'),
  (3, 2, '变化', 'biàn huà', 'change'),
  (3, 3, '经验', 'jīng yàn', 'experience'),
  (3, 4, '机会', 'jī huì', 'opportunity'),
  (3, 5, '成功', 'chéng gōng', 'success'),
  (3, 6, '历史', 'lì shǐ', 'history'),
  (3, 7, '文化', 'wén huà', 'culture'),
  (3, 8, '音乐', 'yīn yuè', 'music'),
  (3, 9, '比赛', 'bǐ sài', 'competition'),
  (3, 10, '地方', 'dì fang', 'place'),
  (3, 11, '环境', 'huán jìng', 'environment'),
  (3, 12, '世界', 'shì jiè', 'world'),
  (3, 13, '社会', 'shè huì', 'society'),
  (3, 14, '经济', 'jīng jì', 'economy'),
  (3, 15, '城市', 'chéng shì', 'city'),
  (3, 16, '国家', 'guó jiā', 'country'),
  (3, 17, '语言', 'yǔ yán', 'language'),
  (3, 18, '新闻', 'xīn wén', 'news'),
  (3, 19, '健康', 'jiàn kāng', 'healthy'),
  (3, 20, '安全', 'ān quán', 'safe'),
  (3, 21, '方便', 'fāng biàn', 'convenient'),
  (3, 22, '简单', 'jiǎn dān', 'simple'),
  (3, 23, '复杂', 'fù zá', 'complex'),
  (3, 24, '特别', 'tè bié', 'special'),
  (3, 25, '普通', 'pǔ tōng', 'ordinary'),
  (3, 26, '认真', 'rèn zhēn', 'serious'),
  (3, 27, '紧张', 'jǐn zhāng', 'nervous'),
  (3, 28, '害怕', 'hài pà', 'afraid'),
  (3, 29, '担心', 'dān xīn', 'worry'),
  (3, 30, '满意', 'mǎn yì', 'satisfied'),
  (3, 31, '失望', 'shī wàng', 'disappointed'),
  (3, 32, '感兴趣', 'gǎn xìng qù', 'interested'),
  (3, 33, '选择', 'xuǎn zé', 'choose'),
  (3, 34, '同意', 'tóng yì', 'agree'),
  (3, 35, '拒绝', 'jù jué', 'refuse'),
  (3, 36, '接受', 'jiē shòu', 'accept'),
  (3, 37, '解释', 'jiě shì', 'explain'),
  (3, 38, '讨论', 'tǎo lùn', 'discuss'),
  (3, 39, '注意', 'zhù yì', 'attention'),
  (3, 40, '影响', 'yǐng xiǎng', 'influence'),
  (3, 41, '保护', 'bǎo hù', 'protect'),
  (3, 42, '提高', 'tí gāo', 'improve'),
  (3, 43, '发展', 'fā zhǎn', 'develop'),
  (3, 44, '解决', 'jiě jué', 'solve'),
  (3, 45, '表示', 'biǎo shì', 'express'),
  (3, 46, '参加', 'cān jiā', 'participate'),
  (3, 47, '离开', 'lí kāi', 'leave'),
  (3, 48, '关心', 'guān xīn', 'care about'),
  (3, 49, '照顾', 'zhào gù', 'take care of'),
  (3, 50, '习惯', 'xí guàn', 'habit'),
  (3, 51, '练习', 'liàn xí', 'practice'),
  (3, 52, '努力', 'nǔ lì', 'effort'),
  (3, 53, '关系', 'guān xi', 'relationship'),
  (3, 54, '办法', 'bàn fǎ', 'method'),
  (3, 55, '原因', 'yuán yīn', 'reason'),
  (3, 56, '结果', 'jié guǒ', 'result'),
  (3, 57, '条件', 'tiáo jiàn', 'condition'),
  (3, 58, '计划', 'jì huà', 'plan'),
  (3, 59, '春天', 'chūn tiān', 'spring'),
  (3, 60, '夏天', 'xià tiān', 'summer'),
  (3, 61, '秋天', 'qiū tiān', 'autumn'),
  (3, 62, '冬天', 'dōng tiān', 'winter'),
  (3, 63, '太阳', 'tài yáng', 'sun'),
  (3, 64, '月亮', 'yuè liang', 'moon'),
  (3, 65, '地图', 'dì tú', 'map'),
  (3, 66, '照片', 'zhào piàn', 'photo'),
  (3, 67, '礼物', 'lǐ wù', 'gift'),
  (3, 68, '节日', 'jié rì', 'holiday'),
  (3, 69, '生日', 'shēng rì', 'birthday'),
  (3, 70, '邻居', 'lín jū', 'neighbor')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

-- =====================================================
-- HSK 4 (50 words)
-- =====================================================
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (4, 1, '交通', 'jiāo tōng', 'traffic'),
  (4, 2, '教育', 'jiào yù', 'education'),
  (4, 3, '科学', 'kē xué', 'science'),
  (4, 4, '技术', 'jì shù', 'technology'),
  (4, 5, '法律', 'fǎ lǜ', 'law'),
  (4, 6, '艺术', 'yì shù', 'art'),
  (4, 7, '态度', 'tài dù', 'attitude'),
  (4, 8, '优点', 'yōu diǎn', 'advantage'),
  (4, 9, '缺点', 'quē diǎn', 'disadvantage'),
  (4, 10, '性格', 'xìng gé', 'personality'),
  (4, 11, '印象', 'yìn xiàng', 'impression'),
  (4, 12, '经理', 'jīng lǐ', 'manager'),
  (4, 13, '作家', 'zuò jiā', 'writer'),
  (4, 14, '记者', 'jì zhě', 'journalist'),
  (4, 15, '律师', 'lǜ shī', 'lawyer'),
  (4, 16, '科学家', 'kē xué jiā', 'scientist'),
  (4, 17, '演员', 'yǎn yuán', 'actor'),
  (4, 18, '警察', 'jǐng chá', 'police'),
  (4, 19, '护士', 'hù shi', 'nurse'),
  (4, 20, '翻译', 'fān yì', 'translate'),
  (4, 21, '招聘', 'zhāo pìn', 'recruit'),
  (4, 22, '竞争', 'jìng zhēng', 'compete'),
  (4, 23, '合作', 'hé zuò', 'cooperate'),
  (4, 24, '沟通', 'gōu tōng', 'communicate'),
  (4, 25, '道歉', 'dào qiàn', 'apologize'),
  (4, 26, '鼓励', 'gǔ lì', 'encourage'),
  (4, 27, '批评', 'pī píng', 'criticize'),
  (4, 28, '表扬', 'biǎo yáng', 'praise'),
  (4, 29, '尊重', 'zūn zhòng', 'respect'),
  (4, 30, '勇敢', 'yǒng gǎn', 'brave'),
  (4, 31, '诚实', 'chéng shí', 'honest'),
  (4, 32, '耐心', 'nài xīn', 'patient'),
  (4, 33, '自信', 'zì xìn', 'confident'),
  (4, 34, '骄傲', 'jiāo ào', 'proud'),
  (4, 35, '害羞', 'hài xiū', 'shy'),
  (4, 36, '无聊', 'wú liáo', 'bored'),
  (4, 37, '兴奋', 'xīng fèn', 'excited'),
  (4, 38, '后悔', 'hòu huǐ', 'regret'),
  (4, 39, '感动', 'gǎn dòng', 'moved/touched'),
  (4, 40, '污染', 'wū rǎn', 'pollution'),
  (4, 41, '垃圾', 'lā jī', 'garbage'),
  (4, 42, '节约', 'jié yuē', 'save/conserve'),
  (4, 43, '减少', 'jiǎn shǎo', 'reduce'),
  (4, 44, '增加', 'zēng jiā', 'increase'),
  (4, 45, '改变', 'gǎi biàn', 'change'),
  (4, 46, '适合', 'shì hé', 'suitable'),
  (4, 47, '严格', 'yán gé', 'strict'),
  (4, 48, '丰富', 'fēng fù', 'rich/abundant'),
  (4, 49, '正式', 'zhèng shì', 'formal'),
  (4, 50, '积极', 'jī jí', 'positive')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

-- =====================================================
-- HSK 5 (50 words)
-- =====================================================
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (5, 1, '安慰', 'ānwèi', 'comfort'),
  (5, 2, '熬夜', 'áoyè', 'stay up late'),
  (5, 3, '宝贵', 'bǎoguì', 'valuable'),
  (5, 4, '保存', 'bǎocún', 'preserve'),
  (5, 5, '保留', 'bǎoliú', 'retain'),
  (5, 6, '悲观', 'bēiguān', 'pessimistic'),
  (5, 7, '背景', 'bèijǐng', 'background'),
  (5, 8, '比例', 'bǐlì', 'proportion'),
  (5, 9, '比如', 'bǐrú', 'for example'),
  (5, 10, '彼此', 'bǐcǐ', 'each other'),
  (5, 11, '毕竟', 'bìjìng', 'after all'),
  (5, 12, '避免', 'bìmiǎn', 'avoid'),
  (5, 13, '编辑', 'biānjí', 'edit'),
  (5, 14, '辩论', 'biànlùn', 'debate'),
  (5, 15, '标准', 'biāozhǔn', 'standard'),
  (5, 16, '表面', 'biǎomiàn', 'surface'),
  (5, 17, '补充', 'bǔchōng', 'supplement'),
  (5, 18, '不断', 'búduàn', 'continuously'),
  (5, 19, '不然', 'bùrán', 'otherwise'),
  (5, 20, '财产', 'cáichǎn', 'property'),
  (5, 21, '采取', 'cǎiqǔ', 'adopt/take'),
  (5, 22, '操作', 'cāozuò', 'operate'),
  (5, 23, '测量', 'cèliáng', 'measure'),
  (5, 24, '曾经', 'céngjīng', 'once'),
  (5, 25, '差距', 'chājù', 'gap'),
  (5, 26, '产品', 'chǎnpǐn', 'product'),
  (5, 27, '常识', 'chángshì', 'common sense'),
  (5, 28, '成分', 'chéngfèn', 'component'),
  (5, 29, '成果', 'chéngguǒ', 'achievement'),
  (5, 30, '成就', 'chéngjiù', 'accomplishment'),
  (5, 31, '成熟', 'chéngshú', 'mature'),
  (5, 32, '成长', 'chéngzhǎng', 'grow up'),
  (5, 33, '承认', 'chéngrèn', 'admit'),
  (5, 34, '程度', 'chéngdù', 'degree'),
  (5, 35, '充满', 'chōngmǎn', 'full of'),
  (5, 36, '出版', 'chūbǎn', 'publish'),
  (5, 37, '出色', 'chūsè', 'outstanding'),
  (5, 38, '传播', 'chuánbō', 'spread'),
  (5, 39, '创造', 'chuàngzào', 'create'),
  (5, 40, '词汇', 'cíhuì', 'vocabulary'),
  (5, 41, '促进', 'cùjìn', 'promote'),
  (5, 42, '存在', 'cúnzài', 'exist'),
  (5, 43, '达到', 'dádào', 'achieve'),
  (5, 44, '导致', 'dǎozhì', 'cause'),
  (5, 45, '独立', 'dúlì', 'independent'),
  (5, 46, '对象', 'duìxiàng', 'object/target'),
  (5, 47, '发愁', 'fāchóu', 'worried'),
  (5, 48, '发明', 'fāmíng', 'invention'),
  (5, 49, '繁荣', 'fánróng', 'prosperity'),
  (5, 50, '反映', 'fǎnyìng', 'reflect')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

-- =====================================================
-- VERIFY SEED DATA
-- =====================================================
SELECT 
  hsk_level,
  COUNT(*) as word_count
FROM hsk_vocabulary
GROUP BY hsk_level
ORDER BY hsk_level;
