-- =====================================================
-- HSK 4 — Upper Intermediate (600 words)
-- Run in Supabase SQL Editor
-- =====================================================
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (4, 1, '交通', 'jiāo tōng', 'traffic'),
  (4, 2, '教育', 'jiào yù', 'education'),
  (4, 3, '科学', 'kē xué', 'science'),
  (4, 4, '技术', 'jì shù', 'technology'),
  (4, 5, '法律', 'fǎ lǜ', 'law'),
  (4, 6, '艺术', 'yì shù', 'art'),
  (4, 7, '态度', 'tài dù', 'attitude'),
  (4, 8, '优点', 'yōu diǎn', 'advantage'),
  (4, 9, '缺点', 'quē diǎn', 'disadvantage'),
  (4, 10, '性格', 'xìng gé', 'personality'),
  (4, 11, '印象', 'yìn xiàng', 'impression'),
  (4, 12, '经理', 'jīng lǐ', 'manager'),
  (4, 13, '作家', 'zuò jiā', 'writer'),
  (4, 14, '记者', 'jì zhě', 'journalist'),
  (4, 15, '律师', 'lǜ shī', 'lawyer'),
  (4, 16, '科学家', 'kē xué jiā', 'scientist'),
  (4, 17, '演员', 'yǎn yuán', 'actor'),
  (4, 18, '警察', 'jǐng chá', 'police'),
  (4, 19, '护士', 'hù shi', 'nurse'),
  (4, 20, '翻译', 'fān yì', 'translate'),
  (4, 21, '招聘', 'zhāo pìn', 'recruit'),
  (4, 22, '竞争', 'jìng zhēng', 'compete'),
  (4, 23, '合作', 'hé zuò', 'cooperate'),
  (4, 24, '沟通', 'gōu tōng', 'communicate'),
  (4, 25, '道歉', 'dào qiàn', 'apologize'),
  (4, 26, '鼓励', 'gǔ lì', 'encourage'),
  (4, 27, '批评', 'pī píng', 'criticize'),
  (4, 28, '表扬', 'biǎo yáng', 'praise'),
  (4, 29, '尊重', 'zūn zhòng', 'respect'),
  (4, 30, '勇敢', 'yǒng gǎn', 'brave'),
  (4, 31, '诚实', 'chéng shí', 'honest'),
  (4, 32, '耐心', 'nài xīn', 'patient'),
  (4, 33, '自信', 'zì xìn', 'confident'),
  (4, 34, '骄傲', 'jiāo ào', 'proud'),
  (4, 35, '害羞', 'hài xiū', 'shy'),
  (4, 36, '无聊', 'wú liáo', 'bored'),
  (4, 37, '兴奋', 'xīng fèn', 'excited'),
  (4, 38, '后悔', 'hòu huǐ', 'regret'),
  (4, 39, '感动', 'gǎn dòng', 'moved/touched'),
  (4, 40, '污染', 'wū rǎn', 'pollution'),
  (4, 41, '垃圾', 'lā jī', 'garbage'),
  (4, 42, '节约', 'jié yuē', 'save/conserve'),
  (4, 43, '减少', 'jiǎn shǎo', 'reduce'),
  (4, 44, '增加', 'zēng jiā', 'increase'),
  (4, 45, '改变', 'gǎi biàn', 'change'),
  (4, 46, '适合', 'shì hé', 'suitable'),
  (4, 47, '严格', 'yán gé', 'strict'),
  (4, 48, '丰富', 'fēng fù', 'rich/abundant'),
  (4, 49, '正式', 'zhèng shì', 'formal'),
  (4, 50, '积极', 'jī jí', 'positive'),
  (4, 51, '消极', 'xiāo jí', 'negative/passive'),
  (4, 52, '乐观', 'lè guān', 'optimistic'),
  (4, 53, '悲观', 'bēi guān', 'pessimistic'),
  (4, 54, '抱歉', 'bào qiàn', 'sorry'),
  (4, 55, '感激', 'gǎn jī', 'grateful'),
  (4, 56, '同情', 'tóng qíng', 'sympathize'),
  (4, 57, '理解', 'lǐ jiě', 'understand'),
  (4, 58, '误会', 'wù huì', 'misunderstand'),
  (4, 59, '矛盾', 'máo dùn', 'contradiction'),
  (4, 60, '冲突', 'chōng tū', 'conflict'),
  (4, 61, '和平', 'hé píng', 'peace'),
  (4, 62, '战争', 'zhàn zhēng', 'war'),
  (4, 63, '胜利', 'shèng lì', 'victory'),
  (4, 64, '失败', 'shī bài', 'failure'),
  (4, 65, '成就', 'chéng jiù', 'achievement'),
  (4, 66, '贡献', 'gòng xiàn', 'contribution'),
  (4, 67, '责任', 'zé rèn', 'responsibility'),
  (4, 68, '义务', 'yì wù', 'duty/obligation'),
  (4, 69, '权利', 'quán lì', 'right'),
  (4, 70, '公平', 'gōng píng', 'fair'),
  (4, 71, '合理', 'hé lǐ', 'reasonable'),
  (4, 72, '制度', 'zhì dù', 'system/institution'),
  (4, 73, '政策', 'zhèng cè', 'policy'),
  (4, 74, '规则', 'guī zé', 'rule'),
  (4, 75, '标准', 'biāo zhǔn', 'standard'),
  (4, 76, '原则', 'yuán zé', 'principle'),
  (4, 77, '道理', 'dào lǐ', 'reason/principle'),
  (4, 78, '事实', 'shì shí', 'fact'),
  (4, 79, '现象', 'xiàn xiàng', 'phenomenon'),
  (4, 80, '过程', 'guò chéng', 'process'),
  (4, 81, '阶段', 'jiē duàn', 'stage'),
  (4, 82, '范围', 'fàn wéi', 'scope/range'),
  (4, 83, '程度', 'chéng dù', 'degree'),
  (4, 84, '数量', 'shù liàng', 'quantity'),
  (4, 85, '质量', 'zhì liàng', 'quality'),
  (4, 86, '效果', 'xiào guǒ', 'effect'),
  (4, 87, '价值', 'jià zhí', 'value'),
  (4, 88, '意义', 'yì yì', 'meaning/significance'),
  (4, 89, '作用', 'zuò yòng', 'function/role'),
  (4, 90, '力量', 'lì liàng', 'strength/power'),
  (4, 91, '压力', 'yā lì', 'pressure'),
  (4, 92, '困难', 'kùn nan', 'difficulty'),
  (4, 93, '挑战', 'tiǎo zhàn', 'challenge'),
  (4, 94, '危险', 'wēi xiǎn', 'danger'),
  (4, 95, '风险', 'fēng xiǎn', 'risk'),
  (4, 96, '优势', 'yōu shì', 'advantage'),
  (4, 97, '特征', 'tè zhēng', 'characteristic'),
  (4, 98, '内容', 'nèi róng', 'content'),
  (4, 99, '形式', 'xíng shì', 'form'),
  (4, 100, '结构', 'jié gòu', 'structure'),
  (4, 101, '方式', 'fāng shì', 'way/method'),
  (4, 102, '方法', 'fāng fǎ', 'method'),
  (4, 103, '目标', 'mù biāo', 'goal/target'),
  (4, 104, '任务', 'rèn wu', 'task'),
  (4, 105, '项目', 'xiàng mù', 'project'),
  (4, 106, '工程', 'gōng chéng', 'engineering'),
  (4, 107, '产业', 'chǎn yè', 'industry'),
  (4, 108, '企业', 'qǐ yè', 'enterprise'),
  (4, 109, '组织', 'zǔ zhī', 'organization'),
  (4, 110, '机构', 'jī gòu', 'institution'),
  (4, 111, '部门', 'bù mén', 'department'),
  (4, 112, '员工', 'yuán gōng', 'employee'),
  (4, 113, '领导', 'lǐng dǎo', 'leader'),
  (4, 114, '管理', 'guǎn lǐ', 'manage'),
  (4, 115, '经营', 'jīng yíng', 'operate/run'),
  (4, 116, '投资', 'tóu zī', 'invest'),
  (4, 117, '利润', 'lì rùn', 'profit'),
  (4, 118, '成本', 'chéng běn', 'cost'),
  (4, 119, '预算', 'yù suàn', 'budget'),
  (4, 120, '收入', 'shōu rù', 'income'),
  (4, 121, '支出', 'zhī chū', 'expenditure'),
  (4, 122, '贸易', 'mào yì', 'trade'),
  (4, 123, '进口', 'jìn kǒu', 'import'),
  (4, 124, '出口', 'chū kǒu', 'export'),
  (4, 125, '市场', 'shì chǎng', 'market'),
  (4, 126, '消费', 'xiāo fèi', 'consume'),
  (4, 127, '购买', 'gòu mǎi', 'purchase'),
  (4, 128, '销售', 'xiāo shòu', 'sell'),
  (4, 129, '品牌', 'pǐn pái', 'brand'),
  (4, 130, '产品', 'chǎn pǐn', 'product'),
  (4, 131, '服务', 'fú wù', 'service'),
  (4, 132, '客户', 'kè hù', 'client'),
  (4, 133, '合同', 'hé tong', 'contract'),
  (4, 134, '协议', 'xié yì', 'agreement'),
  (4, 135, '谈判', 'tán pàn', 'negotiate'),
  (4, 136, '签', 'qiān', 'sign'),
  (4, 137, '取消', 'qǔ xiāo', 'cancel'),
  (4, 138, '推迟', 'tuī chí', 'postpone'),
  (4, 139, '延长', 'yán cháng', 'extend'),
  (4, 140, '恢复', 'huī fù', 'resume/recover'),
  (4, 141, '维持', 'wéi chí', 'maintain'),
  (4, 142, '促进', 'cù jìn', 'promote'),
  (4, 143, '推动', 'tuī dòng', 'push forward'),
  (4, 144, '实施', 'shí shī', 'implement'),
  (4, 145, '执行', 'zhí xíng', 'execute'),
  (4, 146, '完善', 'wán shàn', 'improve'),
  (4, 147, '改革', 'gǎi gé', 'reform'),
  (4, 148, '创新', 'chuàng xīn', 'innovate'),
  (4, 149, '突破', 'tū pò', 'breakthrough'),
  (4, 150, '稳定', 'wěn dìng', 'stable'),
  (4, 151, '上升', 'shàng shēng', 'rise'),
  (4, 152, '下降', 'xià jiàng', 'decline'),
  (4, 153, '增长', 'zēng zhǎng', 'grow'),
  (4, 154, '降低', 'jiàng dī', 'lower/reduce'),
  (4, 155, '提升', 'tí shēng', 'elevate'),
  (4, 156, '扩大', 'kuò dà', 'expand'),
  (4, 157, '集中', 'jí zhōng', 'concentrate'),
  (4, 158, '统一', 'tǒng yī', 'unify'),
  (4, 159, '团结', 'tuán jié', 'unite'),
  (4, 160, '独立', 'dú lì', 'independent'),
  (4, 161, '依赖', 'yī lài', 'depend on'),
  (4, 162, '互相', 'hù xiāng', 'mutually'),
  (4, 163, '主动', 'zhǔ dòng', 'initiative'),
  (4, 164, '认为', 'rèn wéi', 'think/believe'),
  (4, 165, '怀疑', 'huái yí', 'doubt/suspect'),
  (4, 166, '确定', 'què dìng', 'confirm'),
  (4, 167, '肯定', 'kěn dìng', 'affirm'),
  (4, 168, '否定', 'fǒu dìng', 'deny'),
  (4, 169, '承认', 'chéng rèn', 'admit'),
  (4, 170, '分析', 'fēn xī', 'analyze'),
  (4, 171, '总结', 'zǒng jié', 'summarize'),
  (4, 172, '判断', 'pàn duàn', 'judge'),
  (4, 173, '评价', 'píng jià', 'evaluate'),
  (4, 174, '估计', 'gū jì', 'estimate'),
  (4, 175, '预测', 'yù cè', 'predict'),
  (4, 176, '计算', 'jì suàn', 'calculate'),
  (4, 177, '统计', 'tǒng jì', 'statistics'),
  (4, 178, '记录', 'jì lù', 'record'),
  (4, 179, '登记', 'dēng jì', 'register'),
  (4, 180, '报名', 'bào míng', 'sign up'),
  (4, 181, '申请', 'shēn qǐng', 'apply'),
  (4, 182, '资格', 'zī gé', 'qualification'),
  (4, 183, '要求', 'yāo qiú', 'requirement'),
  (4, 184, '满足', 'mǎn zú', 'satisfy'),
  (4, 185, '符合', 'fú hé', 'conform to'),
  (4, 186, '违反', 'wéi fǎn', 'violate'),
  (4, 187, '遵守', 'zūn shǒu', 'comply'),
  (4, 188, '惩罚', 'chéng fá', 'punish'),
  (4, 189, '奖励', 'jiǎng lì', 'reward'),
  (4, 190, '荣誉', 'róng yù', 'honor'),
  (4, 191, '地位', 'dì wèi', 'status'),
  (4, 192, '身份', 'shēn fèn', 'identity'),
  (4, 193, '角色', 'jué sè', 'role'),
  (4, 194, '形象', 'xíng xiàng', 'image'),
  (4, 195, '风格', 'fēng gé', 'style'),
  (4, 196, '魅力', 'mèi lì', 'charm'),
  (4, 197, '智慧', 'zhì huì', 'wisdom'),
  (4, 198, '才能', 'cái néng', 'talent'),
  (4, 199, '想象', 'xiǎng xiàng', 'imagination'),
  (4, 200, '创造', 'chuàng zào', 'create'),
  (4, 201, '设计', 'shè jì', 'design'),
  (4, 202, '发明', 'fā míng', 'invent'),
  (4, 203, '实验', 'shí yàn', 'experiment'),
  (4, 204, '研究', 'yán jiū', 'research'),
  (4, 205, '探索', 'tàn suǒ', 'explore'),
  (4, 206, '发现', 'fā xiàn', 'discover'),
  (4, 207, '证明', 'zhèng míng', 'prove'),
  (4, 208, '描述', 'miáo shù', 'describe'),
  (4, 209, '强调', 'qiáng diào', 'emphasize'),
  (4, 210, '宣布', 'xuān bù', 'announce'),
  (4, 211, '发表', 'fā biǎo', 'publish/express'),
  (4, 212, '报道', 'bào dào', 'report'),
  (4, 213, '采访', 'cǎi fǎng', 'interview'),
  (4, 214, '评论', 'píng lùn', 'comment'),
  (4, 215, '争论', 'zhēng lùn', 'argue'),
  (4, 216, '辩论', 'biàn lùn', 'debate'),
  (4, 217, '商量', 'shāng liáng', 'discuss'),
  (4, 218, '咨询', 'zī xún', 'consult'),
  (4, 219, '建议', 'jiàn yì', 'suggest'),
  (4, 220, '请求', 'qǐng qiú', 'request'),
  (4, 221, '命令', 'mìng lìng', 'command'),
  (4, 222, '允许', 'yǔn xǔ', 'allow'),
  (4, 223, '禁止', 'jìn zhǐ', 'prohibit'),
  (4, 224, '限制', 'xiàn zhì', 'limit'),
  (4, 225, '控制', 'kòng zhì', 'control'),
  (4, 226, '指导', 'zhǐ dǎo', 'guide'),
  (4, 227, '培训', 'péi xùn', 'train'),
  (4, 228, '启发', 'qǐ fā', 'inspire'),
  (4, 229, '吸引', 'xī yǐn', 'attract'),
  (4, 230, '精彩', 'jīng cǎi', 'wonderful'),
  (4, 231, '出色', 'chū sè', 'outstanding'),
  (4, 232, '优秀', 'yōu xiù', 'excellent'),
  (4, 233, '著名', 'zhù míng', 'famous'),
  (4, 234, '普遍', 'pǔ biàn', 'universal'),
  (4, 235, '常见', 'cháng jiàn', 'common'),
  (4, 236, '独特', 'dú tè', 'unique'),
  (4, 237, '典型', 'diǎn xíng', 'typical'),
  (4, 238, '明显', 'míng xiǎn', 'obvious'),
  (4, 239, '显著', 'xiǎn zhù', 'significant'),
  (4, 240, '巨大', 'jù dà', 'huge'),
  (4, 241, '准确', 'zhǔn què', 'accurate'),
  (4, 242, '模糊', 'mó hu', 'vague'),
  (4, 243, '清楚', 'qīng chu', 'clear'),
  (4, 244, '顺利', 'shùn lì', 'smooth'),
  (4, 245, '和谐', 'hé xié', 'harmonious'),
  (4, 246, '平衡', 'píng héng', 'balance'),
  (4, 247, '类似', 'lèi sì', 'similar'),
  (4, 248, '相同', 'xiāng tóng', 'same'),
  (4, 249, '不同', 'bù tóng', 'different'),
  (4, 250, '相反', 'xiāng fǎn', 'opposite'),
  (4, 251, '真实', 'zhēn shí', 'real/true'),
  (4, 252, '客观', 'kè guān', 'objective'),
  (4, 253, '关键', 'guān jiàn', 'key/crucial'),
  (4, 254, '重点', 'zhòng diǎn', 'key point'),
  (4, 255, '基础', 'jī chǔ', 'foundation'),
  (4, 256, '根本', 'gēn běn', 'fundamental'),
  (4, 257, '必要', 'bì yào', 'necessary'),
  (4, 258, '紧急', 'jǐn jí', 'urgent'),
  (4, 259, '及时', 'jí shí', 'timely'),
  (4, 260, '长期', 'cháng qī', 'long-term'),
  (4, 261, '短期', 'duǎn qī', 'short-term'),
  (4, 262, '暂时', 'zàn shí', 'temporary'),
  (4, 263, '逐渐', 'zhú jiàn', 'gradually'),
  (4, 264, '立刻', 'lì kè', 'immediately'),
  (4, 265, '终于', 'zhōng yú', 'finally'),
  (4, 266, '不断', 'bú duàn', 'continuously'),
  (4, 267, '反复', 'fǎn fù', 'repeatedly'),
  (4, 268, '同时', 'tóng shí', 'simultaneously'),
  (4, 269, '幸福', 'xìng fú', 'happiness'),
  (4, 270, '痛苦', 'tòng kǔ', 'suffering'),
  (4, 271, '快乐', 'kuài lè', 'joyful'),
  (4, 272, '悲伤', 'bēi shāng', 'sad'),
  (4, 273, '愤怒', 'fèn nù', 'angry'),
  (4, 274, '恐惧', 'kǒng jù', 'fear'),
  (4, 275, '焦虑', 'jiāo lǜ', 'anxious'),
  (4, 276, '烦恼', 'fán nǎo', 'worry/trouble'),
  (4, 277, '孤独', 'gū dú', 'lonely'),
  (4, 278, '自豪', 'zì háo', 'proud'),
  (4, 279, '期待', 'qī dài', 'look forward to'),
  (4, 280, '渴望', 'kě wàng', 'long for'),
  (4, 281, '热爱', 'rè ài', 'love passionately'),
  (4, 282, '重视', 'zhòng shì', 'value'),
  (4, 283, '关注', 'guān zhù', 'pay attention'),
  (4, 284, '观察', 'guān chá', 'observe'),
  (4, 285, '治疗', 'zhì liáo', 'treat/therapy'),
  (4, 286, '预防', 'yù fáng', 'prevent'),
  (4, 287, '营养', 'yíng yǎng', 'nutrition'),
  (4, 288, '饮食', 'yǐn shí', 'diet'),
  (4, 289, '锻炼', 'duàn liàn', 'exercise'),
  (4, 290, '休息', 'xiū xi', 'rest'),
  (4, 291, '放松', 'fàng sōng', 'relax'),
  (4, 292, '娱乐', 'yú lè', 'entertainment'),
  (4, 293, '爱好', 'ài hào', 'hobby'),
  (4, 294, '小说', 'xiǎo shuō', 'novel'),
  (4, 295, '诗歌', 'shī gē', 'poetry'),
  (4, 296, '演出', 'yǎn chū', 'performance'),
  (4, 297, '展览', 'zhǎn lǎn', 'exhibition'),
  (4, 298, '讲座', 'jiǎng zuò', 'lecture'),
  (4, 299, '会议', 'huì yì', 'meeting'),
  (4, 300, '传统', 'chuán tǒng', 'tradition'),
  (4, 301, '风俗', 'fēng sú', 'custom'),
  (4, 302, '宗教', 'zōng jiào', 'religion'),
  (4, 303, '哲学', 'zhé xué', 'philosophy'),
  (4, 304, '心理', 'xīn lǐ', 'psychology'),
  (4, 305, '精神', 'jīng shén', 'spirit/mental'),
  (4, 306, '意识', 'yì shí', 'consciousness'),
  (4, 307, '思想', 'sī xiǎng', 'thought'),
  (4, 308, '观念', 'guān niàn', 'concept'),
  (4, 309, '理论', 'lǐ lùn', 'theory'),
  (4, 310, '观点', 'guān diǎn', 'viewpoint'),
  (4, 311, '立场', 'lì chǎng', 'standpoint'),
  (4, 312, '角度', 'jiǎo dù', 'angle'),
  (4, 313, '方面', 'fāng miàn', 'aspect'),
  (4, 314, '背景', 'bèi jǐng', 'background'),
  (4, 315, '形势', 'xíng shì', 'situation'),
  (4, 316, '状况', 'zhuàng kuàng', 'condition'),
  (4, 317, '情况', 'qíng kuàng', 'situation'),
  (4, 318, '因素', 'yīn sù', 'factor'),
  (4, 319, '根据', 'gēn jù', 'according to'),
  (4, 320, '理由', 'lǐ yóu', 'reason'),
  (4, 321, '原因', 'yuán yīn', 'cause'),
  (4, 322, '结果', 'jié guǒ', 'result'),
  (4, 323, '影响', 'yǐng xiǎng', 'influence'),
  (4, 324, '后果', 'hòu guǒ', 'consequence'),
  (4, 325, '好处', 'hǎo chu', 'benefit'),
  (4, 326, '利益', 'lì yì', 'interest/benefit'),
  (4, 327, '损失', 'sǔn shī', 'loss'),
  (4, 328, '浪费', 'làng fèi', 'waste'),
  (4, 329, '效率', 'xiào lǜ', 'efficiency'),
  (4, 330, '生产', 'shēng chǎn', 'produce'),
  (4, 331, '制造', 'zhì zào', 'manufacture'),
  (4, 332, '资源', 'zī yuán', 'resource'),
  (4, 333, '能源', 'néng yuán', 'energy'),
  (4, 334, '设备', 'shè bèi', 'equipment'),
  (4, 335, '系统', 'xì tǒng', 'system'),
  (4, 336, '程序', 'chéng xù', 'procedure'),
  (4, 337, '软件', 'ruǎn jiàn', 'software'),
  (4, 338, '数据', 'shù jù', 'data'),
  (4, 339, '网络', 'wǎng luò', 'network'),
  (4, 340, '平台', 'píng tái', 'platform'),
  (4, 341, '功能', 'gōng néng', 'function'),
  (4, 342, '模式', 'mó shì', 'pattern'),
  (4, 343, '更新', 'gēng xīn', 'update'),
  (4, 344, '安装', 'ān zhuāng', 'install'),
  (4, 345, '连接', 'lián jiē', 'connect'),
  (4, 346, '存储', 'cún chǔ', 'store'),
  (4, 347, '删除', 'shān chú', 'delete'),
  (4, 348, '复制', 'fù zhì', 'copy'),
  (4, 349, '编辑', 'biān jí', 'edit'),
  (4, 350, '保存', 'bǎo cún', 'save'),
  (4, 351, '运行', 'yùn xíng', 'run'),
  (4, 352, '操作', 'cāo zuò', 'operate'),
  (4, 353, '处理', 'chǔ lǐ', 'handle'),
  (4, 354, '修复', 'xiū fù', 'fix/repair'),
  (4, 355, '调整', 'tiáo zhěng', 'adjust'),
  (4, 356, '测试', 'cè shì', 'test'),
  (4, 357, '确认', 'què rèn', 'confirm'),
  (4, 358, '欢迎', 'huān yíng', 'welcome'),
  (4, 359, '告别', 'gào bié', 'farewell'),
  (4, 360, '交往', 'jiāo wǎng', 'interact'),
  (4, 361, '相处', 'xiāng chǔ', 'get along'),
  (4, 362, '适应', 'shì yìng', 'adapt'),
  (4, 363, '参与', 'cān yù', 'participate'),
  (4, 364, '承担', 'chéng dān', 'undertake'),
  (4, 365, '忍受', 'rěn shòu', 'tolerate'),
  (4, 366, '克服', 'kè fú', 'overcome'),
  (4, 367, '面对', 'miàn duì', 'face'),
  (4, 368, '熟悉', 'shú xī', 'familiar'),
  (4, 369, '了解', 'liǎo jiě', 'understand'),
  (4, 370, '掌握', 'zhǎng wò', 'master'),
  (4, 371, '利用', 'lì yòng', 'utilize'),
  (4, 372, '发挥', 'fā huī', 'exert'),
  (4, 373, '代表', 'dài biǎo', 'represent'),
  (4, 374, '反映', 'fǎn yìng', 'reflect'),
  (4, 375, '相关', 'xiāng guān', 'related'),
  (4, 376, '以及', 'yǐ jí', 'as well as'),
  (4, 377, '或者', 'huò zhě', 'or'),
  (4, 378, '而且', 'ér qiě', 'moreover'),
  (4, 379, '不仅', 'bù jǐn', 'not only'),
  (4, 380, '另外', 'lìng wài', 'in addition'),
  (4, 381, '此外', 'cǐ wài', 'furthermore'),
  (4, 382, '然而', 'rán ér', 'however'),
  (4, 383, '不过', 'bú guò', 'but/however'),
  (4, 384, '尽管', 'jǐn guǎn', 'despite'),
  (4, 385, '即使', 'jí shǐ', 'even if'),
  (4, 386, '除非', 'chú fēi', 'unless'),
  (4, 387, '只要', 'zhǐ yào', 'as long as'),
  (4, 388, '无论', 'wú lùn', 'regardless'),
  (4, 389, '不管', 'bù guǎn', 'no matter'),
  (4, 390, '总之', 'zǒng zhī', 'in short'),
  (4, 391, '因此', 'yīn cǐ', 'therefore'),
  (4, 392, '从而', 'cóng ér', 'thereby'),
  (4, 393, '于是', 'yú shì', 'thereupon'),
  (4, 394, '既然', 'jì rán', 'since/now that'),
  (4, 395, '假如', 'jiǎ rú', 'supposing'),
  (4, 396, '否则', 'fǒu zé', 'otherwise'),
  (4, 397, '与其', 'yǔ qí', 'rather than'),
  (4, 398, '不如', 'bù rú', 'not as good as'),
  (4, 399, '果然', 'guǒ rán', 'as expected'),
  (4, 400, '居然', 'jū rán', 'unexpectedly'),
  (4, 401, '竟然', 'jìng rán', 'actually'),
  (4, 402, '难道', 'nán dào', 'could it be'),
  (4, 403, '毕竟', 'bì jìng', 'after all'),
  (4, 404, '到底', 'dào dǐ', 'in the end'),
  (4, 405, '恐怕', 'kǒng pà', 'I''m afraid'),
  (4, 406, '大概', 'dà gài', 'roughly'),
  (4, 407, '似乎', 'sì hū', 'seem'),
  (4, 408, '看来', 'kàn lái', 'it seems'),
  (4, 409, '显然', 'xiǎn rán', 'obviously'),
  (4, 410, '当然', 'dāng rán', 'of course'),
  (4, 411, '自然', 'zì rán', 'naturally'),
  (4, 412, '必然', 'bì rán', 'inevitably'),
  (4, 413, '偶然', 'ǒu rán', 'accidentally'),
  (4, 414, '幸亏', 'xìng kuī', 'fortunately'),
  (4, 415, '遗憾', 'yí hàn', 'regret'),
  (4, 416, '可惜', 'kě xī', 'pity'),
  (4, 417, '难免', 'nán miǎn', 'inevitable'),
  (4, 418, '未必', 'wèi bì', 'not necessarily'),
  (4, 419, '不一定', 'bù yí dìng', 'not certain'),
  (4, 420, '一定', 'yí dìng', 'definitely'),
  (4, 421, '大约', 'dà yuē', 'approximately'),
  (4, 422, '将近', 'jiāng jìn', 'nearly'),
  (4, 423, '至少', 'zhì shǎo', 'at least'),
  (4, 424, '至多', 'zhì duō', 'at most'),
  (4, 425, '尤其', 'yóu qí', 'especially'),
  (4, 426, '甚至', 'shèn zhì', 'even'),
  (4, 427, '简直', 'jiǎn zhí', 'simply'),
  (4, 429, '到处', 'dào chù', 'everywhere'),
  (4, 430, '随时', 'suí shí', 'anytime'),
  (4, 431, '随地', 'suí dì', 'anywhere'),
  (4, 432, '随便', 'suí biàn', 'casual'),
  (4, 433, '特意', 'tè yì', 'specially'),
  (4, 434, '故意', 'gù yì', 'deliberately'),
  (4, 435, '无意', 'wú yì', 'unintentionally'),
  (4, 436, '幸运', 'xìng yùn', 'lucky'),
  (4, 437, '倒霉', 'dǎo méi', 'unlucky'),
  (4, 438, '成功', 'chéng gōng', 'success'),
  (4, 440, '进步', 'jìn bù', 'progress'),
  (4, 441, '退步', 'tuì bù', 'regress'),
  (4, 442, '发展', 'fā zhǎn', 'develop'),
  (4, 443, '落后', 'luò hòu', 'fall behind'),
  (4, 444, '先进', 'xiān jìn', 'advanced'),
  (4, 445, '现代', 'xiàn dài', 'modern'),
  (4, 446, '古代', 'gǔ dài', 'ancient'),
  (4, 447, '当代', 'dāng dài', 'contemporary'),
  (4, 448, '未来', 'wèi lái', 'future'),
  (4, 449, '过去', 'guò qù', 'past'),
  (4, 450, '目前', 'mù qián', 'currently'),
  (4, 451, '如今', 'rú jīn', 'nowadays'),
  (4, 452, '从前', 'cóng qián', 'in the past'),
  (4, 453, '将来', 'jiāng lái', 'in the future'),
  (4, 454, '永远', 'yǒng yuǎn', 'forever'),
  (4, 455, '始终', 'shǐ zhōng', 'always'),
  (4, 456, '从来', 'cóng lái', 'always/never'),
  (4, 457, '一向', 'yī xiàng', 'all along'),
  (4, 458, '往往', 'wǎng wǎng', 'often'),
  (4, 459, '频繁', 'pín fán', 'frequent'),
  (4, 460, '偶尔', 'ǒu ěr', 'occasionally'),
  (4, 461, '难得', 'nán dé', 'rare'),
  (4, 462, '照常', 'zhào cháng', 'as usual'),
  (4, 463, '依然', 'yī rán', 'still'),
  (4, 464, '仍然', 'réng rán', 'still'),
  (4, 465, '已经', 'yǐ jīng', 'already'),
  (4, 466, '曾经', 'céng jīng', 'once'),
  (4, 467, '即将', 'jí jiāng', 'about to'),
  (4, 468, '快要', 'kuài yào', 'soon'),
  (4, 469, '刚刚', 'gāng gāng', 'just now'),
  (4, 470, '渐渐', 'jiàn jiàn', 'gradually'),
  (4, 471, '慢慢', 'màn man', 'slowly'),
  (4, 472, '匆忙', 'cōng máng', 'hurried'),
  (4, 473, '急忙', 'jí máng', 'hastily'),
  (4, 474, '赶紧', 'gǎn jǐn', 'hurry up'),
  (4, 475, '赶快', 'gǎn kuài', 'quickly'),
  (4, 476, '尽快', 'jǐn kuài', 'as soon as'),
  (4, 477, '按时', 'àn shí', 'on time'),
  (4, 478, '准时', 'zhǔn shí', 'punctual'),
  (4, 479, '迟到', 'chí dào', 'late'),
  (4, 480, '提前', 'tí qián', 'in advance'),
  (4, 481, '推后', 'tuī hòu', 'postpone'),
  (4, 482, '农业', 'nóng yè', 'agriculture'),
  (4, 483, '工业', 'gōng yè', 'industry'),
  (4, 484, '商业', 'shāng yè', 'commerce'),
  (4, 485, '旅游业', 'lǚ yóu yè', 'tourism'),
  (4, 486, '房地产', 'fáng dì chǎn', 'real estate'),
  (4, 487, '金融', 'jīn róng', 'finance'),
  (4, 488, '银行', 'yín háng', 'bank'),
  (4, 489, '保险', 'bǎo xiǎn', 'insurance'),
  (4, 490, '税收', 'shuì shōu', 'tax'),
  (4, 491, '工资', 'gōng zī', 'salary'),
  (4, 492, '奖金', 'jiǎng jīn', 'bonus'),
  (4, 493, '福利', 'fú lì', 'welfare'),
  (4, 494, '退休', 'tuì xiū', 'retire'),
  (4, 495, '失业', 'shī yè', 'unemployed'),
  (4, 496, '就业', 'jiù yè', 'employment'),
  (4, 497, '创业', 'chuàng yè', 'start business'),
  (4, 499, '辞职', 'cí zhí', 'resign'),
  (4, 500, '解雇', 'jiě gù', 'fire/dismiss'),
  (4, 501, '面试', 'miàn shì', 'interview'),
  (4, 502, '简历', 'jiǎn lì', 'resume'),
  (4, 503, '经历', 'jīng lì', 'experience'),
  (4, 504, '能力', 'néng lì', 'ability'),
  (4, 505, '技能', 'jì néng', 'skill'),
  (4, 506, '学历', 'xué lì', 'education'),
  (4, 507, '文凭', 'wén píng', 'diploma'),
  (4, 508, '证书', 'zhèng shū', 'certificate'),
  (4, 509, '课程', 'kè chéng', 'course'),
  (4, 510, '学期', 'xué qī', 'semester'),
  (4, 511, '学费', 'xué fèi', 'tuition'),
  (4, 512, '奖学金', 'jiǎng xué jīn', 'scholarship'),
  (4, 513, '毕业', 'bì yè', 'graduate'),
  (4, 514, '学位', 'xué wèi', 'degree'),
  (4, 515, '论文', 'lùn wén', 'thesis'),
  (4, 516, '答辩', 'dá biàn', 'defend thesis'),
  (4, 517, '导师', 'dǎo shī', 'advisor'),
  (4, 518, '专家', 'zhuān jiā', 'expert'),
  (4, 519, '学者', 'xué zhě', 'scholar'),
  (4, 520, '大陆', 'dà lù', 'mainland'),
  (4, 521, '半岛', 'bàn dǎo', 'peninsula'),
  (4, 522, '岛屿', 'dǎo yǔ', 'island'),
  (4, 523, '沙漠', 'shā mò', 'desert'),
  (4, 524, '草原', 'cǎo yuán', 'grassland'),
  (4, 525, '高原', 'gāo yuán', 'plateau'),
  (4, 526, '盆地', 'pén dì', 'basin'),
  (4, 527, '平原', 'píng yuán', 'plain'),
  (4, 528, '气候', 'qì hòu', 'climate'),
  (4, 529, '湿度', 'shī dù', 'humidity'),
  (4, 530, '干燥', 'gān zào', 'dry'),
  (4, 531, '潮湿', 'cháo shī', 'humid'),
  (4, 532, '地震', 'dì zhèn', 'earthquake'),
  (4, 533, '洪水', 'hóng shuǐ', 'flood'),
  (4, 534, '台风', 'tái fēng', 'typhoon'),
  (4, 535, '灾害', 'zāi hài', 'disaster'),
  (4, 536, '救援', 'jiù yuán', 'rescue'),
  (4, 537, '志愿者', 'zhì yuàn zhě', 'volunteer'),
  (4, 538, '慈善', 'cí shàn', 'charity'),
  (4, 539, '捐款', 'juān kuǎn', 'donate'),
  (4, 540, '扶贫', 'fú pín', 'poverty relief'),
  (4, 541, '环保', 'huán bǎo', 'environmental'),
  (4, 542, '回收', 'huí shōu', 'recycle'),
  (4, 543, '可持续', 'kě chí xù', 'sustainable'),
  (4, 544, '绿色', 'lǜ sè', 'green'),
  (4, 545, '低碳', 'dī tàn', 'low carbon'),
  (4, 546, '排放', 'pái fàng', 'emissions'),
  (4, 547, '生态', 'shēng tài', 'ecology'),
  (4, 548, '物种', 'wù zhǒng', 'species'),
  (4, 549, '灭绝', 'miè jué', 'extinction'),
  (4, 550, '保护', 'bǎo hù', 'protect'),
  (4, 551, '人口', 'rén kǒu', 'population'),
  (4, 552, '民主', 'mín zhǔ', 'democracy'),
  (4, 553, '自由', 'zì yóu', 'freedom'),
  (4, 554, '平等', 'píng děng', 'equality'),
  (4, 555, '法治', 'fǎ zhì', 'rule of law'),
  (4, 556, '选举', 'xuǎn jǔ', 'election'),
  (4, 557, '投票', 'tóu piào', 'vote'),
  (4, 558, '政府', 'zhèng fǔ', 'government'),
  (4, 559, '国际', 'guó jì', 'international'),
  (4, 560, '外交', 'wài jiāo', 'diplomacy'),
  (4, 562, '全球化', 'quán qiú huà', 'globalization'),
  (4, 563, '多元化', 'duō yuán huà', 'diversify'),
  (4, 564, '信息化', 'xìn xī huà', 'digitization'),
  (4, 565, '城市化', 'chéng shì huà', 'urbanization'),
  (4, 566, '工业化', 'gōng yè huà', 'industrialize'),
  (4, 567, '现代化', 'xiàn dài huà', 'modernize'),
  (4, 568, '自动化', 'zì dòng huà', 'automation'),
  (4, 569, '智能', 'zhì néng', 'intelligent'),
  (4, 570, '人工智能', 'rén gōng zhì néng', 'AI'),
  (4, 571, '机器人', 'jī qì rén', 'robot'),
  (4, 572, '互联网', 'hù lián wǎng', 'internet'),
  (4, 573, '电子商务', 'diàn zǐ shāng wù', 'e-commerce'),
  (4, 574, '移动支付', 'yí dòng zhī fù', 'mobile pay'),
  (4, 575, '社交媒体', 'shè jiāo méi tǐ', 'social media'),
  (4, 576, '虚拟', 'xū nǐ', 'virtual'),
  (4, 577, '现实', 'xiàn shí', 'reality'),
  (4, 578, '数字', 'shù zì', 'digital'),
  (4, 579, '在线', 'zài xiàn', 'online'),
  (4, 580, '离线', 'lí xiàn', 'offline'),
  (4, 581, '注册', 'zhù cè', 'register'),
  (4, 582, '账号', 'zhàng hào', 'account'),
  (4, 583, '密码', 'mì mǎ', 'password'),
  (4, 584, '隐私', 'yǐn sī', 'privacy'),
  (4, 585, '安全', 'ān quán', 'security'),
  (4, 586, '病毒', 'bìng dú', 'virus'),
  (4, 587, '黑客', 'hēi kè', 'hacker'),
  (4, 588, '加密', 'jiā mì', 'encrypt'),
  (4, 589, '解锁', 'jiě suǒ', 'unlock'),
  (4, 590, '充电', 'chōng diàn', 'charge'),
  (4, 591, '电池', 'diàn chí', 'battery'),
  (4, 592, '屏幕', 'píng mù', 'screen'),
  (4, 593, '键盘', 'jiàn pán', 'keyboard'),
  (4, 594, '鼠标', 'shǔ biāo', 'mouse'),
  (4, 595, '打印机', 'dǎ yìn jī', 'printer'),
  (4, 596, '摄像头', 'shè xiàng tóu', 'camera'),
  (4, 597, '耳机', 'ěr jī', 'headphones'),
  (4, 598, '音箱', 'yīn xiāng', 'speaker'),
  (4, 599, '遥控器', 'yáo kòng qì', 'remote'),
  (4, 600, '空调', 'kōng tiáo', 'air conditioner')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

SELECT 'HSK 4 seeded!' AS status, COUNT(*) AS total FROM hsk_vocabulary WHERE hsk_level = 4;
