-- =====================================================
-- HSK 5 — Advanced (630 new words)
-- Run in Supabase SQL Editor
-- =====================================================

-- Part 1: Words 1-200
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (5, 1, '安慰', 'ān wèi', 'comfort'),
  (5, 2, '熬夜', 'áo yè', 'stay up late'),
  (5, 3, '宝贵', 'bǎo guì', 'valuable'),
  (5, 4, '保存', 'bǎo cún', 'preserve'),
  (5, 5, '保留', 'bǎo liú', 'retain'),
  (5, 6, '悲观', 'bēi guān', 'pessimistic'),
  (5, 7, '背景', 'bèi jǐng', 'background'),
  (5, 8, '比例', 'bǐ lì', 'proportion'),
  (5, 9, '比如', 'bǐ rú', 'for example'),
  (5, 10, '彼此', 'bǐ cǐ', 'each other'),
  (5, 11, '毕竟', 'bì jìng', 'after all'),
  (5, 12, '避免', 'bì miǎn', 'avoid'),
  (5, 13, '编辑', 'biān jí', 'edit'),
  (5, 14, '辩论', 'biàn lùn', 'debate'),
  (5, 15, '标准', 'biāo zhǔn', 'standard'),
  (5, 16, '表面', 'biǎo miàn', 'surface'),
  (5, 17, '补充', 'bǔ chōng', 'supplement'),
  (5, 18, '不断', 'bú duàn', 'continuously'),
  (5, 19, '不然', 'bù rán', 'otherwise'),
  (5, 20, '财产', 'cái chǎn', 'property'),
  (5, 21, '采取', 'cǎi qǔ', 'adopt/take'),
  (5, 22, '操作', 'cāo zuò', 'operate'),
  (5, 23, '测量', 'cè liáng', 'measure'),
  (5, 24, '曾经', 'céng jīng', 'once'),
  (5, 25, '差距', 'chā jù', 'gap'),
  (5, 26, '产品', 'chǎn pǐn', 'product'),
  (5, 27, '常识', 'cháng shì', 'common sense'),
  (5, 28, '成分', 'chéng fèn', 'component'),
  (5, 29, '成果', 'chéng guǒ', 'achievement'),
  (5, 30, '成就', 'chéng jiù', 'accomplishment'),
  (5, 31, '成熟', 'chéng shú', 'mature'),
  (5, 32, '成长', 'chéng zhǎng', 'grow up'),
  (5, 33, '承认', 'chéng rèn', 'admit'),
  (5, 34, '程度', 'chéng dù', 'degree'),
  (5, 35, '充满', 'chōng mǎn', 'full of'),
  (5, 36, '出版', 'chū bǎn', 'publish'),
  (5, 37, '出色', 'chū sè', 'outstanding'),
  (5, 38, '传播', 'chuán bō', 'spread'),
  (5, 39, '创造', 'chuàng zào', 'create'),
  (5, 40, '词汇', 'cí huì', 'vocabulary'),
  (5, 41, '促进', 'cù jìn', 'promote'),
  (5, 42, '存在', 'cún zài', 'exist'),
  (5, 43, '达到', 'dá dào', 'achieve'),
  (5, 44, '导致', 'dǎo zhì', 'cause'),
  (5, 45, '独立', 'dú lì', 'independent'),
  (5, 46, '对象', 'duì xiàng', 'object/target'),
  (5, 47, '发愁', 'fā chóu', 'worried'),
  (5, 48, '发明', 'fā míng', 'invention'),
  (5, 49, '繁荣', 'fán róng', 'prosperity'),
  (5, 50, '反映', 'fǎn yìng', 'reflect'),
  (5, 51, '方案', 'fāng àn', 'plan/scheme'),
  (5, 52, '妨碍', 'fáng ài', 'hinder'),
  (5, 53, '仿佛', 'fǎng fú', 'as if'),
  (5, 54, '非凡', 'fēi fán', 'extraordinary'),
  (5, 55, '分布', 'fēn bù', 'distribute'),
  (5, 56, '分配', 'fēn pèi', 'allocate'),
  (5, 57, '奋斗', 'fèn dòu', 'struggle/strive'),
  (5, 58, '风险', 'fēng xiǎn', 'risk'),
  (5, 59, '疯狂', 'fēng kuáng', 'crazy'),
  (5, 60, '讽刺', 'fěng cì', 'satire/irony'),
  (5, 61, '服从', 'fú cóng', 'obey'),
  (5, 62, '幅度', 'fú dù', 'range/extent'),
  (5, 63, '辅导', 'fǔ dǎo', 'tutor'),
  (5, 64, '负担', 'fù dān', 'burden'),
  (5, 65, '复制', 'fù zhì', 'duplicate'),
  (5, 66, '改善', 'gǎi shàn', 'improve'),
  (5, 67, '概括', 'gài kuò', 'summarize'),
  (5, 68, '概念', 'gài niàn', 'concept'),
  (5, 69, '干脆', 'gān cuì', 'straightforward'),
  (5, 70, '赶紧', 'gǎn jǐn', 'hurry up'),
  (5, 71, '感受', 'gǎn shòu', 'feeling/sense'),
  (5, 72, '高档', 'gāo dàng', 'high-end'),
  (5, 73, '格局', 'gé jú', 'pattern/layout'),
  (5, 74, '根本', 'gēn běn', 'fundamental'),
  (5, 75, '根据', 'gēn jù', 'according to'),
  (5, 76, '工厂', 'gōng chǎng', 'factory'),
  (5, 77, '公布', 'gōng bù', 'announce'),
  (5, 78, '公开', 'gōng kāi', 'public/open'),
  (5, 79, '公认', 'gōng rèn', 'publicly recognized'),
  (5, 80, '公寓', 'gōng yù', 'apartment'),
  (5, 81, '功能', 'gōng néng', 'function'),
  (5, 82, '贡献', 'gòng xiàn', 'contribution'),
  (5, 83, '沟通', 'gōu tōng', 'communicate'),
  (5, 84, '构成', 'gòu chéng', 'constitute'),
  (5, 85, '姑且', 'gū qiě', 'for the time being'),
  (5, 86, '股票', 'gǔ piào', 'stocks'),
  (5, 87, '固定', 'gù dìng', 'fixed'),
  (5, 88, '挂号', 'guà hào', 'register'),
  (5, 89, '关怀', 'guān huái', 'care'),
  (5, 90, '观察', 'guān chá', 'observe'),
  (5, 91, '观点', 'guān diǎn', 'viewpoint'),
  (5, 92, '官方', 'guān fāng', 'official'),
  (5, 93, '管理', 'guǎn lǐ', 'manage'),
  (5, 94, '光滑', 'guāng huá', 'smooth'),
  (5, 95, '广泛', 'guǎng fàn', 'extensive'),
  (5, 96, '规律', 'guī lǜ', 'law/pattern'),
  (5, 97, '规模', 'guī mó', 'scale'),
  (5, 98, '规则', 'guī zé', 'rule'),
  (5, 99, '贵族', 'guì zú', 'aristocrat'),
  (5, 100, '国籍', 'guó jí', 'nationality'),
  (5, 101, '过分', 'guò fèn', 'excessive'),
  (5, 102, '过渡', 'guò dù', 'transition'),
  (5, 103, '海关', 'hǎi guān', 'customs'),
  (5, 104, '含义', 'hán yì', 'meaning'),
  (5, 105, '行业', 'háng yè', 'industry'),
  (5, 106, '豪华', 'háo huá', 'luxurious'),
  (5, 107, '好奇', 'hào qí', 'curious'),
  (5, 108, '何必', 'hé bì', 'why bother'),
  (5, 109, '何况', 'hé kuàng', 'let alone'),
  (5, 110, '和谐', 'hé xié', 'harmonious'),
  (5, 111, '核心', 'hé xīn', 'core'),
  (5, 112, '后果', 'hòu guǒ', 'consequence'),
  (5, 113, '忽视', 'hū shì', 'neglect'),
  (5, 114, '互联网', 'hù lián wǎng', 'internet'),
  (5, 115, '华裔', 'huá yì', 'overseas Chinese'),
  (5, 116, '化学', 'huà xué', 'chemistry'),
  (5, 117, '话题', 'huà tí', 'topic'),
  (5, 118, '缓解', 'huǎn jiě', 'relieve'),
  (5, 119, '幻想', 'huàn xiǎng', 'fantasy'),
  (5, 120, '荒谬', 'huāng miù', 'absurd'),
  (5, 121, '灰尘', 'huī chén', 'dust'),
  (5, 122, '灰心', 'huī xīn', 'discouraged'),
  (5, 123, '恢复', 'huī fù', 'recover'),
  (5, 124, '汇率', 'huì lǜ', 'exchange rate'),
  (5, 125, '混合', 'hùn hé', 'mix'),
  (5, 126, '活跃', 'huó yuè', 'active'),
  (5, 127, '机器', 'jī qì', 'machine'),
  (5, 128, '基本', 'jī běn', 'basic'),
  (5, 129, '基础', 'jī chǔ', 'foundation'),
  (5, 130, '激烈', 'jī liè', 'intense'),
  (5, 131, '及时', 'jí shí', 'timely'),
  (5, 132, '即使', 'jí shǐ', 'even if'),
  (5, 133, '集体', 'jí tǐ', 'collective'),
  (5, 134, '集中', 'jí zhōng', 'concentrate'),
  (5, 135, '纪录', 'jì lù', 'record'),
  (5, 136, '纪律', 'jì lǜ', 'discipline'),
  (5, 137, '纪念', 'jì niàn', 'commemorate'),
  (5, 138, '技巧', 'jì qiǎo', 'skill/technique'),
  (5, 139, '寂寞', 'jì mò', 'lonely'),
  (5, 140, '家乡', 'jiā xiāng', 'hometown'),
  (5, 141, '嘉宾', 'jiā bīn', 'honored guest'),
  (5, 142, '假设', 'jiǎ shè', 'hypothesis'),
  (5, 143, '假装', 'jiǎ zhuāng', 'pretend'),
  (5, 144, '价值', 'jià zhí', 'value'),
  (5, 145, '驾驶', 'jià shǐ', 'drive'),
  (5, 146, '坚定', 'jiān dìng', 'firm'),
  (5, 147, '坚固', 'jiān gù', 'solid'),
  (5, 148, '坚决', 'jiān jué', 'resolute'),
  (5, 149, '艰巨', 'jiān jù', 'arduous'),
  (5, 150, '艰苦', 'jiān kǔ', 'hardship'),
  (5, 151, '剪刀', 'jiǎn dāo', 'scissors'),
  (5, 152, '简历', 'jiǎn lì', 'resume'),
  (5, 153, '建立', 'jiàn lì', 'establish'),
  (5, 154, '建设', 'jiàn shè', 'construct'),
  (5, 155, '建筑', 'jiàn zhù', 'architecture'),
  (5, 156, '健身', 'jiàn shēn', 'fitness'),
  (5, 157, '讲究', 'jiǎng jiu', 'particular about'),
  (5, 158, '讲座', 'jiǎng zuò', 'lecture'),
  (5, 159, '交换', 'jiāo huàn', 'exchange'),
  (5, 160, '交际', 'jiāo jì', 'socialize'),
  (5, 161, '角度', 'jiǎo dù', 'angle'),
  (5, 162, '教材', 'jiào cái', 'textbook'),
  (5, 163, '教练', 'jiào liàn', 'coach'),
  (5, 164, '教训', 'jiào xun', 'lesson'),
  (5, 165, '阶段', 'jiē duàn', 'stage'),
  (5, 166, '接触', 'jiē chù', 'contact'),
  (5, 167, '接待', 'jiē dài', 'receive/host'),
  (5, 168, '接近', 'jiē jìn', 'approach'),
  (5, 169, '结合', 'jié hé', 'combine'),
  (5, 170, '结构', 'jié gòu', 'structure'),
  (5, 171, '结论', 'jié lùn', 'conclusion'),
  (5, 172, '结账', 'jié zhàng', 'pay the bill'),
  (5, 173, '节奏', 'jié zòu', 'rhythm'),
  (5, 174, '解放', 'jiě fàng', 'liberate'),
  (5, 175, '借口', 'jiè kǒu', 'excuse'),
  (5, 176, '金属', 'jīn shǔ', 'metal'),
  (5, 177, '尽力', 'jìn lì', 'do one''s best'),
  (5, 178, '尽量', 'jǐn liàng', 'as much as possible'),
  (5, 179, '紧迫', 'jǐn pò', 'pressing'),
  (5, 180, '谨慎', 'jǐn shèn', 'cautious'),
  (5, 181, '进口', 'jìn kǒu', 'import'),
  (5, 182, '精力', 'jīng lì', 'energy'),
  (5, 183, '精确', 'jīng què', 'precise'),
  (5, 184, '精神', 'jīng shén', 'spirit'),
  (5, 185, '经典', 'jīng diǎn', 'classic'),
  (5, 186, '经商', 'jīng shāng', 'do business'),
  (5, 187, '景色', 'jǐng sè', 'scenery'),
  (5, 188, '敬佩', 'jìng pèi', 'admire'),
  (5, 189, '竞争', 'jìng zhēng', 'competition'),
  (5, 190, '纠正', 'jiū zhèng', 'correct'),
  (5, 191, '救护车', 'jiù hù chē', 'ambulance'),
  (5, 192, '居民', 'jū mín', 'resident'),
  (5, 193, '局势', 'jú shì', 'situation'),
  (5, 194, '举办', 'jǔ bàn', 'hold/host'),
  (5, 195, '具备', 'jù bèi', 'possess'),
  (5, 196, '具体', 'jù tǐ', 'specific'),
  (5, 197, '聚会', 'jù huì', 'gathering'),
  (5, 198, '决心', 'jué xīn', 'determination'),
  (5, 199, '角色', 'jué sè', 'role'),
  (5, 200, '绝对', 'jué duì', 'absolute')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

-- Part 2: Words 201-400
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (5, 201, '军事', 'jūn shì', 'military'),
  (5, 202, '均匀', 'jūn yún', 'even/uniform'),
  (5, 203, '开发', 'kāi fā', 'develop'),
  (5, 204, '开放', 'kāi fàng', 'open up'),
  (5, 205, '开幕式', 'kāi mù shì', 'opening ceremony'),
  (5, 206, '开拓', 'kāi tuò', 'pioneer'),
  (5, 207, '刊物', 'kān wù', 'publication'),
  (5, 208, '看不起', 'kàn bu qǐ', 'look down on'),
  (5, 209, '看望', 'kàn wàng', 'visit'),
  (5, 210, '靠', 'kào', 'rely on'),
  (5, 211, '可靠', 'kě kào', 'reliable'),
  (5, 212, '可怕', 'kě pà', 'terrible'),
  (5, 213, '刻苦', 'kè kǔ', 'hardworking'),
  (5, 214, '客观', 'kè guān', 'objective'),
  (5, 215, '课题', 'kè tí', 'topic/subject'),
  (5, 216, '空间', 'kōng jiān', 'space'),
  (5, 217, '空前', 'kōng qián', 'unprecedented'),
  (5, 218, '控制', 'kòng zhì', 'control'),
  (5, 219, '口味', 'kǒu wèi', 'taste'),
  (5, 220, '夸张', 'kuā zhāng', 'exaggerate'),
  (5, 221, '会计', 'kuài jì', 'accounting'),
  (5, 222, '宽容', 'kuān róng', 'tolerant'),
  (5, 223, '矿产', 'kuàng chǎn', 'mineral'),
  (5, 224, '亏损', 'kuī sǔn', 'loss'),
  (5, 225, '扩大', 'kuò dà', 'expand'),
  (5, 226, '来源', 'lái yuán', 'source'),
  (5, 227, '浪漫', 'làng màn', 'romantic'),
  (5, 228, '劳动', 'láo dòng', 'labor'),
  (5, 229, '乐趣', 'lè qù', 'pleasure'),
  (5, 230, '类型', 'lèi xíng', 'type'),
  (5, 231, '冷淡', 'lěng dàn', 'cold/indifferent'),
  (5, 232, '理论', 'lǐ lùn', 'theory'),
  (5, 233, '理想', 'lǐ xiǎng', 'ideal'),
  (5, 234, '力量', 'lì liàng', 'strength'),
  (5, 235, '利润', 'lì rùn', 'profit'),
  (5, 236, '利息', 'lì xī', 'interest'),
  (5, 237, '利益', 'lì yì', 'interest/benefit'),
  (5, 238, '立即', 'lì jí', 'immediately'),
  (5, 239, '联合', 'lián hé', 'unite'),
  (5, 240, '联想', 'lián xiǎng', 'associate'),
  (5, 241, '恋爱', 'liàn ài', 'romance'),
  (5, 242, '良好', 'liáng hǎo', 'good'),
  (5, 243, '粮食', 'liáng shi', 'grain/food'),
  (5, 244, '灵活', 'líng huó', 'flexible'),
  (5, 245, '灵魂', 'líng hún', 'soul'),
  (5, 246, '领域', 'lǐng yù', 'field/domain'),
  (5, 247, '流传', 'liú chuán', 'spread'),
  (5, 248, '流利', 'liú lì', 'fluent'),
  (5, 249, '流行', 'liú xíng', 'popular'),
  (5, 250, '龙', 'lóng', 'dragon'),
  (5, 251, '漏洞', 'lòu dòng', 'loophole'),
  (5, 252, '陆续', 'lù xù', 'successively'),
  (5, 253, '录取', 'lù qǔ', 'admit/enroll'),
  (5, 254, '论文', 'lùn wén', 'thesis'),
  (5, 255, '逻辑', 'luó ji', 'logic'),
  (5, 256, '落后', 'luò hòu', 'fall behind'),
  (5, 257, '满足', 'mǎn zú', 'satisfy'),
  (5, 258, '矛盾', 'máo dùn', 'contradiction'),
  (5, 259, '冒险', 'mào xiǎn', 'adventure'),
  (5, 260, '贸易', 'mào yì', 'trade'),
  (5, 261, '媒体', 'méi tǐ', 'media'),
  (5, 262, '美术', 'měi shù', 'fine arts'),
  (5, 263, '魅力', 'mèi lì', 'charm'),
  (5, 264, '梦想', 'mèng xiǎng', 'dream'),
  (5, 265, '密度', 'mì dù', 'density'),
  (5, 266, '密封', 'mì fēng', 'seal'),
  (5, 267, '密切', 'mì qiè', 'close/intimate'),
  (5, 268, '面积', 'miàn jī', 'area'),
  (5, 269, '面临', 'miàn lín', 'face'),
  (5, 270, '描写', 'miáo xiě', 'describe'),
  (5, 271, '敏感', 'mǐn gǎn', 'sensitive'),
  (5, 272, '名牌', 'míng pái', 'famous brand'),
  (5, 273, '名胜古迹', 'míng shèng gǔ jì', 'scenic spots'),
  (5, 274, '明确', 'míng què', 'clear/explicit'),
  (5, 275, '明显', 'míng xiǎn', 'obvious'),
  (5, 276, '明星', 'míng xīng', 'star/celebrity'),
  (5, 277, '命令', 'mìng lìng', 'command'),
  (5, 278, '命运', 'mìng yùn', 'fate/destiny'),
  (5, 279, '模仿', 'mó fǎng', 'imitate'),
  (5, 280, '模糊', 'mó hu', 'vague'),
  (5, 281, '模型', 'mó xíng', 'model'),
  (5, 282, '摩擦', 'mó cā', 'friction'),
  (5, 283, '陌生', 'mò shēng', 'unfamiliar'),
  (5, 284, '目标', 'mù biāo', 'goal'),
  (5, 285, '目前', 'mù qián', 'currently'),
  (5, 286, '目录', 'mù lù', 'catalog'),
  (5, 287, '内部', 'nèi bù', 'internal'),
  (5, 288, '内涵', 'nèi hán', 'connotation'),
  (5, 289, '难怪', 'nán guài', 'no wonder'),
  (5, 290, '难免', 'nán miǎn', 'inevitable'),
  (5, 291, '脑袋', 'nǎo dai', 'head/brain'),
  (5, 292, '能源', 'néng yuán', 'energy'),
  (5, 293, '年代', 'nián dài', 'era/decade'),
  (5, 294, '年纪', 'nián jì', 'age'),
  (5, 295, '念', 'niàn', 'read/miss'),
  (5, 296, '宁可', 'nìng kě', 'would rather'),
  (5, 297, '浓厚', 'nóng hòu', 'strong/thick'),
  (5, 298, '农村', 'nóng cūn', 'rural/village'),
  (5, 299, '农民', 'nóng mín', 'farmer'),
  (5, 300, '农业', 'nóng yè', 'agriculture'),
  (5, 301, '偶然', 'ǒu rán', 'accidental'),
  (5, 302, '拍摄', 'pāi shè', 'film/shoot'),
  (5, 303, '排列', 'pái liè', 'arrange'),
  (5, 304, '派', 'pài', 'send/faction'),
  (5, 305, '盼望', 'pàn wàng', 'look forward to'),
  (5, 306, '培养', 'péi yǎng', 'cultivate'),
  (5, 307, '赔偿', 'péi cháng', 'compensate'),
  (5, 308, '配合', 'pèi hé', 'cooperate'),
  (5, 309, '批准', 'pī zhǔn', 'approve'),
  (5, 310, '疲劳', 'pí láo', 'fatigue'),
  (5, 311, '片面', 'piàn miàn', 'one-sided'),
  (5, 312, '频率', 'pín lǜ', 'frequency'),
  (5, 313, '品种', 'pǐn zhǒng', 'variety'),
  (5, 314, '平等', 'píng děng', 'equality'),
  (5, 315, '平衡', 'píng héng', 'balance'),
  (5, 316, '平静', 'píng jìng', 'calm'),
  (5, 317, '评估', 'píng gū', 'evaluate'),
  (5, 318, '评价', 'píng jià', 'assess'),
  (5, 319, '迫切', 'pò qiè', 'urgent'),
  (5, 320, '破产', 'pò chǎn', 'bankrupt'),
  (5, 321, '破坏', 'pò huài', 'destroy'),
  (5, 322, '朴素', 'pǔ sù', 'simple/plain'),
  (5, 323, '普遍', 'pǔ biàn', 'universal'),
  (5, 324, '期望', 'qī wàng', 'expect'),
  (5, 325, '期限', 'qī xiàn', 'deadline'),
  (5, 326, '其余', 'qí yú', 'the rest'),
  (5, 327, '奇妙', 'qí miào', 'wonderful'),
  (5, 328, '启发', 'qǐ fā', 'inspire'),
  (5, 329, '企图', 'qǐ tú', 'attempt'),
  (5, 330, '企业', 'qǐ yè', 'enterprise'),
  (5, 331, '气氛', 'qì fēn', 'atmosphere'),
  (5, 332, '气候', 'qì hòu', 'climate'),
  (5, 333, '谦虚', 'qiān xū', 'modest'),
  (5, 334, '签订', 'qiān dìng', 'sign/conclude'),
  (5, 335, '前途', 'qián tú', 'future/prospect'),
  (5, 336, '浅', 'qiǎn', 'shallow'),
  (5, 337, '强制', 'qiáng zhì', 'force'),
  (5, 338, '抢', 'qiǎng', 'grab/rob'),
  (5, 339, '亲切', 'qīn qiè', 'warm/cordial'),
  (5, 340, '亲自', 'qīn zì', 'personally'),
  (5, 341, '勤奋', 'qín fèn', 'diligent'),
  (5, 342, '青春', 'qīng chūn', 'youth'),
  (5, 343, '青少年', 'qīng shào nián', 'teenagers'),
  (5, 344, '清淡', 'qīng dàn', 'light/mild'),
  (5, 345, '情景', 'qíng jǐng', 'scene'),
  (5, 346, '情绪', 'qíng xù', 'emotion'),
  (5, 347, '请教', 'qǐng jiào', 'consult/ask'),
  (5, 348, '庆祝', 'qìng zhù', 'celebrate'),
  (5, 349, '球迷', 'qiú mí', 'sports fan'),
  (5, 350, '趋势', 'qū shì', 'trend'),
  (5, 351, '取消', 'qǔ xiāo', 'cancel'),
  (5, 352, '全局', 'quán jú', 'overall'),
  (5, 353, '全面', 'quán miàn', 'comprehensive'),
  (5, 354, '权力', 'quán lì', 'power'),
  (5, 355, '权利', 'quán lì', 'right'),
  (5, 356, '缺乏', 'quē fá', 'lack'),
  (5, 357, '确保', 'què bǎo', 'ensure'),
  (5, 358, '确定', 'què dìng', 'determine'),
  (5, 359, '确认', 'què rèn', 'confirm'),
  (5, 360, '群体', 'qún tǐ', 'group'),
  (5, 361, '燃烧', 'rán shāo', 'burn'),
  (5, 362, '人才', 'rén cái', 'talent'),
  (5, 363, '人口', 'rén kǒu', 'population'),
  (5, 364, '人类', 'rén lèi', 'mankind'),
  (5, 365, '人民', 'rén mín', 'people'),
  (5, 366, '人生', 'rén shēng', 'life'),
  (5, 367, '人事', 'rén shì', 'personnel'),
  (5, 368, '人物', 'rén wù', 'figure/character'),
  (5, 369, '人员', 'rén yuán', 'personnel'),
  (5, 370, '忍不住', 'rěn bu zhù', 'can''t help'),
  (5, 371, '任何', 'rèn hé', 'any'),
  (5, 372, '任命', 'rèn mìng', 'appoint'),
  (5, 373, '任务', 'rèn wu', 'task'),
  (5, 374, '仍然', 'réng rán', 'still'),
  (5, 375, '日常', 'rì cháng', 'daily'),
  (5, 376, '日程', 'rì chéng', 'schedule'),
  (5, 377, '日益', 'rì yì', 'increasingly'),
  (5, 378, '融化', 'róng huà', 'melt'),
  (5, 379, '如何', 'rú hé', 'how'),
  (5, 380, '如今', 'rú jīn', 'nowadays'),
  (5, 381, '软件', 'ruǎn jiàn', 'software'),
  (5, 382, '弱', 'ruò', 'weak'),
  (5, 383, '丧失', 'sàng shī', 'lose'),
  (5, 384, '扫描', 'sǎo miáo', 'scan'),
  (5, 385, '色彩', 'sè cǎi', 'color'),
  (5, 386, '沙漠', 'shā mò', 'desert'),
  (5, 387, '删除', 'shān chú', 'delete'),
  (5, 388, '善良', 'shàn liáng', 'kind'),
  (5, 389, '善于', 'shàn yú', 'good at'),
  (5, 390, '商品', 'shāng pǐn', 'commodity'),
  (5, 391, '商务', 'shāng wù', 'business'),
  (5, 392, '商业', 'shāng yè', 'commerce'),
  (5, 393, '上当', 'shàng dàng', 'be fooled'),
  (5, 394, '设备', 'shè bèi', 'equipment'),
  (5, 395, '设施', 'shè shī', 'facility'),
  (5, 396, '设想', 'shè xiǎng', 'envisage'),
  (5, 397, '社区', 'shè qū', 'community'),
  (5, 398, '摄影', 'shè yǐng', 'photography'),
  (5, 399, '深刻', 'shēn kè', 'profound'),
  (5, 400, '神秘', 'shén mì', 'mysterious')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

-- Part 3: Words 401-630
INSERT INTO hsk_vocabulary (hsk_level, word_order, hanzi, pinyin, english) VALUES
  (5, 401, '审查', 'shěn chá', 'review/censor'),
  (5, 402, '慎重', 'shèn zhòng', 'prudent'),
  (5, 403, '升', 'shēng', 'rise/liter'),
  (5, 404, '生产', 'shēng chǎn', 'produce'),
  (5, 405, '生动', 'shēng dòng', 'vivid'),
  (5, 406, '生活', 'shēng huó', 'life'),
  (5, 407, '生命', 'shēng mìng', 'life'),
  (5, 408, '声明', 'shēng míng', 'statement'),
  (5, 409, '声音', 'shēng yīn', 'sound'),
  (5, 410, '胜利', 'shèng lì', 'victory'),
  (5, 411, '失眠', 'shī mián', 'insomnia'),
  (5, 412, '失去', 'shī qù', 'lose'),
  (5, 413, '实话', 'shí huà', 'truth'),
  (5, 414, '实际', 'shí jì', 'actual'),
  (5, 415, '实践', 'shí jiàn', 'practice'),
  (5, 416, '实力', 'shí lì', 'strength'),
  (5, 417, '实施', 'shí shī', 'implement'),
  (5, 418, '实现', 'shí xiàn', 'realize'),
  (5, 419, '实行', 'shí xíng', 'carry out'),
  (5, 420, '实质', 'shí zhì', 'essence'),
  (5, 421, '食物', 'shí wù', 'food'),
  (5, 422, '使命', 'shǐ mìng', 'mission'),
  (5, 423, '始终', 'shǐ zhōng', 'always'),
  (5, 424, '示范', 'shì fàn', 'demonstrate'),
  (5, 425, '事业', 'shì yè', 'career'),
  (5, 426, '事先', 'shì xiān', 'beforehand'),
  (5, 427, '试卷', 'shì juàn', 'exam paper'),
  (5, 428, '收藏', 'shōu cáng', 'collect'),
  (5, 429, '收获', 'shōu huò', 'harvest'),
  (5, 430, '手工', 'shǒu gōng', 'handicraft'),
  (5, 431, '手术', 'shǒu shù', 'surgery'),
  (5, 432, '手续', 'shǒu xù', 'procedures'),
  (5, 433, '首先', 'shǒu xiān', 'first of all'),
  (5, 434, '寿命', 'shòu mìng', 'lifespan'),
  (5, 435, '受伤', 'shòu shāng', 'injured'),
  (5, 436, '书法', 'shū fǎ', 'calligraphy'),
  (5, 437, '输入', 'shū rù', 'input'),
  (5, 438, '蔬菜', 'shū cài', 'vegetables'),
  (5, 439, '舒适', 'shū shì', 'comfortable'),
  (5, 440, '熟练', 'shú liàn', 'skilled'),
  (5, 441, '属于', 'shǔ yú', 'belong to'),
  (5, 442, '数码', 'shù mǎ', 'digital'),
  (5, 443, '数据', 'shù jù', 'data'),
  (5, 444, '摔', 'shuāi', 'fall/throw'),
  (5, 445, '双方', 'shuāng fāng', 'both sides'),
  (5, 446, '丝毫', 'sī háo', 'slightest'),
  (5, 447, '丝绸', 'sī chóu', 'silk'),
  (5, 448, '思考', 'sī kǎo', 'think'),
  (5, 449, '思维', 'sī wéi', 'thinking'),
  (5, 450, '思想', 'sī xiǎng', 'thought'),
  (5, 451, '私人', 'sī rén', 'private'),
  (5, 452, '素质', 'sù zhì', 'quality'),
  (5, 453, '速度', 'sù dù', 'speed'),
  (5, 454, '塑造', 'sù zào', 'shape/mold'),
  (5, 455, '损失', 'sǔn shī', 'loss'),
  (5, 456, '缩短', 'suō duǎn', 'shorten'),
  (5, 457, '所谓', 'suǒ wèi', 'so-called'),
  (5, 458, '太极拳', 'tài jí quán', 'tai chi'),
  (5, 459, '谈判', 'tán pàn', 'negotiate'),
  (5, 460, '弹性', 'tán xìng', 'elasticity'),
  (5, 461, '坦率', 'tǎn shuài', 'frank'),
  (5, 462, '探索', 'tàn suǒ', 'explore'),
  (5, 463, '逃避', 'táo bì', 'escape/avoid'),
  (5, 464, '逃跑', 'táo pǎo', 'flee'),
  (5, 465, '特色', 'tè sè', 'feature'),
  (5, 466, '特殊', 'tè shū', 'special'),
  (5, 467, '特征', 'tè zhēng', 'characteristic'),
  (5, 468, '提倡', 'tí chàng', 'advocate'),
  (5, 469, '提纲', 'tí gāng', 'outline'),
  (5, 470, '提问', 'tí wèn', 'ask a question'),
  (5, 471, '体会', 'tǐ huì', 'realize'),
  (5, 472, '体积', 'tǐ jī', 'volume'),
  (5, 473, '体系', 'tǐ xì', 'system'),
  (5, 474, '体验', 'tǐ yàn', 'experience'),
  (5, 475, '天赋', 'tiān fù', 'talent'),
  (5, 476, '天真', 'tiān zhēn', 'naive'),
  (5, 477, '调查', 'diào chá', 'investigate'),
  (5, 478, '调整', 'tiáo zhěng', 'adjust'),
  (5, 479, '挑战', 'tiǎo zhàn', 'challenge'),
  (5, 480, '通常', 'tōng cháng', 'usually'),
  (5, 481, '通讯', 'tōng xùn', 'communication'),
  (5, 482, '同胞', 'tóng bāo', 'compatriot'),
  (5, 483, '统计', 'tǒng jì', 'statistics'),
  (5, 484, '统一', 'tǒng yī', 'unify'),
  (5, 485, '痛苦', 'tòng kǔ', 'pain'),
  (5, 486, '投入', 'tóu rù', 'invest/throw in'),
  (5, 487, '投诉', 'tóu sù', 'complain'),
  (5, 488, '投资', 'tóu zī', 'invest'),
  (5, 489, '透明', 'tòu míng', 'transparent'),
  (5, 490, '突出', 'tū chū', 'prominent'),
  (5, 491, '途径', 'tú jìng', 'way/channel'),
  (5, 492, '团队', 'tuán duì', 'team'),
  (5, 493, '推广', 'tuī guǎng', 'promote'),
  (5, 494, '推荐', 'tuī jiàn', 'recommend'),
  (5, 495, '退步', 'tuì bù', 'regress'),
  (5, 496, '退休', 'tuì xiū', 'retire'),
  (5, 497, '妥协', 'tuǒ xié', 'compromise'),
  (5, 498, '外交', 'wài jiāo', 'diplomacy'),
  (5, 499, '完美', 'wán měi', 'perfect'),
  (5, 500, '完整', 'wán zhěng', 'complete'),
  (5, 501, '危机', 'wēi jī', 'crisis'),
  (5, 502, '威胁', 'wēi xié', 'threaten'),
  (5, 503, '微笑', 'wēi xiào', 'smile'),
  (5, 504, '违反', 'wéi fǎn', 'violate'),
  (5, 505, '围绕', 'wéi rào', 'surround'),
  (5, 506, '唯一', 'wéi yī', 'only/sole'),
  (5, 507, '维护', 'wéi hù', 'maintain'),
  (5, 508, '伟大', 'wěi dà', 'great'),
  (5, 509, '未必', 'wèi bì', 'not necessarily'),
  (5, 510, '未来', 'wèi lái', 'future'),
  (5, 511, '位于', 'wèi yú', 'located at'),
  (5, 512, '温暖', 'wēn nuǎn', 'warm'),
  (5, 513, '文件', 'wén jiàn', 'document'),
  (5, 514, '文明', 'wén míng', 'civilization'),
  (5, 515, '文学', 'wén xué', 'literature'),
  (5, 516, '闻', 'wén', 'smell/hear'),
  (5, 517, '稳定', 'wěn dìng', 'stable'),
  (5, 518, '无奈', 'wú nài', 'helpless'),
  (5, 519, '无数', 'wú shù', 'countless'),
  (5, 520, '武器', 'wǔ qì', 'weapon'),
  (5, 521, '武术', 'wǔ shù', 'martial arts'),
  (5, 522, '物质', 'wù zhì', 'material'),
  (5, 523, '西方', 'xī fāng', 'western'),
  (5, 524, '吸收', 'xī shōu', 'absorb'),
  (5, 525, '系列', 'xì liè', 'series'),
  (5, 526, '细节', 'xì jié', 'detail'),
  (5, 527, '下载', 'xià zài', 'download'),
  (5, 528, '鲜明', 'xiān míng', 'vivid'),
  (5, 529, '显得', 'xiǎn de', 'appear'),
  (5, 530, '显然', 'xiǎn rán', 'obviously'),
  (5, 531, '显示', 'xiǎn shì', 'display'),
  (5, 532, '现代', 'xiàn dài', 'modern'),
  (5, 533, '现实', 'xiàn shí', 'reality'),
  (5, 534, '现象', 'xiàn xiàng', 'phenomenon'),
  (5, 535, '限制', 'xiàn zhì', 'limit'),
  (5, 536, '相当', 'xiāng dāng', 'quite'),
  (5, 537, '相对', 'xiāng duì', 'relatively'),
  (5, 538, '相关', 'xiāng guān', 'related'),
  (5, 539, '相似', 'xiāng sì', 'similar'),
  (5, 540, '详细', 'xiáng xì', 'detailed'),
  (5, 541, '享受', 'xiǎng shòu', 'enjoy'),
  (5, 542, '项目', 'xiàng mù', 'project'),
  (5, 543, '消除', 'xiāo chú', 'eliminate'),
  (5, 544, '消费', 'xiāo fèi', 'consume'),
  (5, 545, '消化', 'xiāo huà', 'digest'),
  (5, 546, '消失', 'xiāo shī', 'disappear'),
  (5, 547, '销售', 'xiāo shòu', 'sales'),
  (5, 548, '小气', 'xiǎo qi', 'stingy'),
  (5, 549, '效率', 'xiào lǜ', 'efficiency'),
  (5, 550, '效益', 'xiào yì', 'benefit'),
  (5, 551, '协调', 'xié tiáo', 'coordinate'),
  (5, 552, '心态', 'xīn tài', 'mentality'),
  (5, 553, '心理', 'xīn lǐ', 'psychology'),
  (5, 554, '欣赏', 'xīn shǎng', 'appreciate'),
  (5, 555, '新颖', 'xīn yǐng', 'novel'),
  (5, 556, '信号', 'xìn hào', 'signal'),
  (5, 557, '信任', 'xìn rèn', 'trust'),
  (5, 558, '信息', 'xìn xī', 'information'),
  (5, 559, '兴趣', 'xìng qù', 'interest'),
  (5, 560, '行为', 'xíng wéi', 'behavior'),
  (5, 561, '形成', 'xíng chéng', 'form'),
  (5, 562, '形容', 'xíng róng', 'describe'),
  (5, 563, '形式', 'xíng shì', 'form'),
  (5, 564, '形势', 'xíng shì', 'situation'),
  (5, 565, '形象', 'xíng xiàng', 'image'),
  (5, 566, '性质', 'xìng zhì', 'nature'),
  (5, 567, '幸运', 'xìng yùn', 'lucky'),
  (5, 568, '修改', 'xiū gǎi', 'revise'),
  (5, 569, '虚假', 'xū jiǎ', 'false'),
  (5, 570, '虚心', 'xū xīn', 'open-minded'),
  (5, 571, '需求', 'xū qiú', 'demand'),
  (5, 572, '叙述', 'xù shù', 'narrate'),
  (5, 573, '宣传', 'xuān chuán', 'publicize'),
  (5, 574, '学历', 'xué lì', 'education'),
  (5, 575, '学术', 'xué shù', 'academic'),
  (5, 576, '学问', 'xué wen', 'knowledge'),
  (5, 577, '血', 'xuè', 'blood'),
  (5, 578, '寻找', 'xún zhǎo', 'search for'),
  (5, 579, '迅速', 'xùn sù', 'rapid'),
  (5, 580, '压力', 'yā lì', 'pressure'),
  (5, 581, '延伸', 'yán shēn', 'extend'),
  (5, 582, '严肃', 'yán sù', 'serious'),
  (5, 583, '演变', 'yǎn biàn', 'evolve'),
  (5, 584, '演讲', 'yǎn jiǎng', 'speech'),
  (5, 585, '宴会', 'yàn huì', 'banquet'),
  (5, 586, '阳光', 'yáng guāng', 'sunshine'),
  (5, 587, '样式', 'yàng shì', 'style'),
  (5, 588, '要素', 'yào sù', 'element'),
  (5, 589, '业务', 'yè wù', 'business'),
  (5, 590, '业余', 'yè yú', 'amateur'),
  (5, 591, '一律', 'yī lǜ', 'without exception'),
  (5, 592, '依旧', 'yī jiù', 'as before'),
  (5, 593, '依据', 'yī jù', 'basis'),
  (5, 594, '依靠', 'yī kào', 'rely on'),
  (5, 595, '一致', 'yī zhì', 'consistent'),
  (5, 596, '遗产', 'yí chǎn', 'heritage'),
  (5, 597, '疑问', 'yí wèn', 'question/doubt'),
  (5, 598, '意识', 'yì shí', 'consciousness'),
  (5, 599, '意外', 'yì wài', 'unexpected'),
  (5, 600, '意味着', 'yì wèi zhe', 'means'),
  (5, 601, '因素', 'yīn sù', 'factor'),
  (5, 602, '引导', 'yǐn dǎo', 'guide'),
  (5, 603, '引起', 'yǐn qǐ', 'cause'),
  (5, 604, '印刷', 'yìn shuā', 'print'),
  (5, 605, '英雄', 'yīng xióng', 'hero'),
  (5, 606, '应付', 'yìng fu', 'cope with'),
  (5, 607, '应用', 'yìng yòng', 'apply'),
  (5, 608, '营业', 'yíng yè', 'business'),
  (5, 609, '影子', 'yǐng zi', 'shadow'),
  (5, 610, '硬件', 'yìng jiàn', 'hardware'),
  (5, 611, '拥抱', 'yōng bào', 'embrace'),
  (5, 612, '拥有', 'yōng yǒu', 'possess'),
  (5, 613, '永恒', 'yǒng héng', 'eternal'),
  (5, 614, '勇气', 'yǒng qì', 'courage'),
  (5, 615, '优惠', 'yōu huì', 'discount'),
  (5, 616, '优美', 'yōu měi', 'beautiful'),
  (5, 617, '优势', 'yōu shì', 'advantage'),
  (5, 618, '悠久', 'yōu jiǔ', 'long-standing'),
  (5, 619, '犹豫', 'yóu yù', 'hesitate'),
  (5, 620, '有利', 'yǒu lì', 'favorable'),
  (5, 621, '与其', 'yǔ qí', 'rather than'),
  (5, 622, '预报', 'yù bào', 'forecast'),
  (5, 623, '预订', 'yù dìng', 'reserve'),
  (5, 624, '元素', 'yuán sù', 'element'),
  (5, 625, '原理', 'yuán lǐ', 'principle'),
  (5, 626, '原始', 'yuán shǐ', 'primitive'),
  (5, 627, '愿望', 'yuàn wàng', 'wish'),
  (5, 628, '运输', 'yùn shū', 'transport'),
  (5, 629, '运用', 'yùn yòng', 'apply'),
  (5, 630, '灾难', 'zāi nàn', 'disaster'),
  (5, 631, '在乎', 'zài hu', 'care about'),
  (5, 632, '在于', 'zài yú', 'lie in'),
  (5, 633, '赞美', 'zàn měi', 'praise'),
  (5, 634, '造成', 'zào chéng', 'cause'),
  (5, 635, '责备', 'zé bèi', 'blame'),
  (5, 636, '增添', 'zēng tiān', 'add'),
  (5, 637, '摘要', 'zhāi yào', 'abstract'),
  (5, 638, '展开', 'zhǎn kāi', 'unfold'),
  (5, 639, '展望', 'zhǎn wàng', 'look ahead'),
  (5, 640, '占领', 'zhàn lǐng', 'occupy'),
  (5, 641, '战略', 'zhàn lüè', 'strategy'),
  (5, 642, '战术', 'zhàn shù', 'tactics'),
  (5, 643, '章节', 'zhāng jié', 'chapter'),
  (5, 644, '掌握', 'zhǎng wò', 'grasp'),
  (5, 645, '招待', 'zhāo dài', 'entertain'),
  (5, 646, '哲学', 'zhé xué', 'philosophy'),
  (5, 647, '珍惜', 'zhēn xī', 'cherish'),
  (5, 648, '真诚', 'zhēn chéng', 'sincere'),
  (5, 649, '真实', 'zhēn shí', 'real'),
  (5, 650, '阵容', 'zhèn róng', 'lineup'),
  (5, 651, '振奋', 'zhèn fèn', 'inspire'),
  (5, 652, '征求', 'zhēng qiú', 'solicit'),
  (5, 653, '整体', 'zhěng tǐ', 'whole'),
  (5, 654, '正常', 'zhèng cháng', 'normal'),
  (5, 655, '正当', 'zhèng dāng', 'legitimate'),
  (5, 656, '证据', 'zhèng jù', 'evidence'),
  (5, 657, '政府', 'zhèng fǔ', 'government'),
  (5, 658, '政治', 'zhèng zhì', 'politics'),
  (5, 659, '支撑', 'zhī chēng', 'support'),
  (5, 660, '支持', 'zhī chí', 'support'),
  (5, 661, '知识', 'zhī shi', 'knowledge'),
  (5, 662, '执行', 'zhí xíng', 'execute'),
  (5, 663, '职能', 'zhí néng', 'function'),
  (5, 664, '职位', 'zhí wèi', 'position'),
  (5, 665, '职业', 'zhí yè', 'profession'),
  (5, 666, '制定', 'zhì dìng', 'formulate'),
  (5, 667, '制度', 'zhì dù', 'system'),
  (5, 668, '制造', 'zhì zào', 'manufacture'),
  (5, 669, '志愿者', 'zhì yuàn zhě', 'volunteer'),
  (5, 670, '治理', 'zhì lǐ', 'govern'),
  (5, 671, '秩序', 'zhì xù', 'order'),
  (5, 672, '智力', 'zhì lì', 'intelligence'),
  (5, 673, '智能', 'zhì néng', 'intelligent'),
  (5, 674, '中介', 'zhōng jiè', 'intermediary'),
  (5, 675, '中心', 'zhōng xīn', 'center'),
  (5, 676, '忠诚', 'zhōng chéng', 'loyal'),
  (5, 677, '种类', 'zhǒng lèi', 'category'),
  (5, 678, '重大', 'zhòng dà', 'major'),
  (5, 679, '重量', 'zhòng liàng', 'weight'),
  (5, 680, '周围', 'zhōu wéi', 'surrounding'),
  (5, 681, '逐步', 'zhú bù', 'step by step'),
  (5, 682, '主持', 'zhǔ chí', 'host/preside'),
  (5, 683, '主观', 'zhǔ guān', 'subjective'),
  (5, 684, '主题', 'zhǔ tí', 'theme'),
  (5, 685, '主张', 'zhǔ zhāng', 'advocate'),
  (5, 686, '注册', 'zhù cè', 'register'),
  (5, 687, '著作', 'zhù zuò', 'work/writing'),
  (5, 688, '抓紧', 'zhuā jǐn', 'seize'),
  (5, 689, '专家', 'zhuān jiā', 'expert'),
  (5, 690, '专门', 'zhuān mén', 'specially'),
  (5, 691, '转变', 'zhuǎn biàn', 'transform'),
  (5, 692, '转化', 'zhuǎn huà', 'convert'),
  (5, 693, '装饰', 'zhuāng shì', 'decorate'),
  (5, 694, '状态', 'zhuàng tài', 'state'),
  (5, 695, '追求', 'zhuī qiú', 'pursue'),
  (5, 696, '资格', 'zī gé', 'qualification'),
  (5, 697, '资金', 'zī jīn', 'capital'),
  (5, 698, '资料', 'zī liào', 'data/material'),
  (5, 699, '资源', 'zī yuán', 'resource'),
  (5, 700, '自从', 'zì cóng', 'since'),
  (5, 701, '自动', 'zì dòng', 'automatic'),
  (5, 702, '自发', 'zì fā', 'spontaneous'),
  (5, 703, '自豪', 'zì háo', 'proud'),
  (5, 704, '自觉', 'zì jué', 'conscious'),
  (5, 705, '自律', 'zì lǜ', 'self-discipline'),
  (5, 706, '自身', 'zì shēn', 'oneself'),
  (5, 707, '自私', 'zì sī', 'selfish'),
  (5, 708, '自由', 'zì yóu', 'freedom'),
  (5, 709, '自愿', 'zì yuàn', 'voluntary'),
  (5, 710, '综合', 'zōng hé', 'comprehensive'),
  (5, 711, '总裁', 'zǒng cái', 'CEO'),
  (5, 712, '总共', 'zǒng gòng', 'altogether'),
  (5, 713, '总理', 'zǒng lǐ', 'premier'),
  (5, 714, '总统', 'zǒng tǒng', 'president'),
  (5, 715, '走私', 'zǒu sī', 'smuggle'),
  (5, 716, '租金', 'zū jīn', 'rent'),
  (5, 717, '组成', 'zǔ chéng', 'compose'),
  (5, 718, '组合', 'zǔ hé', 'combination'),
  (5, 719, '阻碍', 'zǔ ài', 'obstruct'),
  (5, 720, '最初', 'zuì chū', 'initially'),
  (5, 721, '尊敬', 'zūn jìng', 'respect'),
  (5, 722, '遵守', 'zūn shǒu', 'comply'),
  (5, 723, '作品', 'zuò pǐn', 'work/piece'),
  (5, 724, '作为', 'zuò wéi', 'as/act as'),
  (5, 725, '座位', 'zuò wèi', 'seat')
ON CONFLICT (hsk_level, hanzi) DO UPDATE SET pinyin = EXCLUDED.pinyin, english = EXCLUDED.english, word_order = EXCLUDED.word_order;

-- Verify
SELECT 'HSK 5 seeded!' AS status, COUNT(*) AS total FROM hsk_vocabulary WHERE hsk_level = 5;
